Repository TeamSparker/Spark-Android, pull requests merged in 2022-01, with the labels that each got.

#3 #1 [chore] 초기세팅
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/SparkApplication.kt
  app/src/main/java/com/spark/android/ui/base/BaseActivity.kt
  app/src/main/java/com/spark/android/ui/base/BaseFragment.kt
  app/src/main/java/com/spark/android/utill/BindingAdapters.kt
  build.gradle
Labels: 🐷창환, pull request

#11 #4 feature/바텀네비게이션 세팅 완료
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/MainActivity.kt
  app/src/main/java/com/spark/android/ui/MainActivity.kt
  app/src/main/java/com/spark/android/ui/home/FeedFragment.kt
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
  app/src/main/java/com/spark/android/ui/home/StorageFragment.kt
  app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt
  app/src/main/res/color/selector_bottom_navigation.xml
  app/src/main/res/drawable/ic_bottom_navigation_feed.xml
  app/src/main/res/drawable/ic_bottom_navigation_home.xml
  app/src/main/res/drawable/ic_bottom_navigation_storage.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_home_main.xml
  app/src/main/res/layout/fragment_storage.xml
  app/src/main/res/menu/menu_main_bottom_navigation.xml
  app/src/main/res/values/strings.xml
Labels: 🐷창환, feat, pull request

#12 #10 [스플래쉬] 스플래쉬 화면 추가 및 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/ui/intro/IntroActivity.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/drawable-hdpi/bg_intro.png
  app/src/main/res/drawable-hdpi/ic_intro_title.png
  app/src/main/res/drawable-mdpi/bg_intro.png
  app/src/main/res/drawable-mdpi/ic_intro_title.png
  app/src/main/res/drawable-xhdpi/bg_intro.png
  app/src/main/res/drawable-xhdpi/ic_intro_title.png
  app/src/main/res/drawable-xxhdpi/bg_intro.png
  app/src/main/res/drawable-xxhdpi/ic_intro_title.png
  app/src/main/res/drawable-xxxhdpi/bg_intro.png
  app/src/main/res/drawable-xxxhdpi/ic_intro_title.png
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#16 #5 [습관방] 습관방 디자인
  app/src/main/java/com/spark/android/ui/habit/HabitFragment.kt
  app/src/main/res/drawable/bg_habit_box_scroll_gradation.xml
  app/src/main/res/drawable/bg_habit_cut_line.xml
  app/src/main/res/drawable/bg_habit_sparkflake1.xml
  app/src/main/res/drawable/bg_habit_sparkflake2.xml
  app/src/main/res/drawable/bg_habit_sparkflake3.xml
  app/src/main/res/drawable/bg_habit_sparkflake4.xml
  app/src/main/res/drawable/bg_habit_sparkflake5.xml
  app/src/main/res/drawable/bg_habit_sparkflake6.xml
  app/src/main/res/drawable/bg_habit_today_active.xml
  app/src/main/res/drawable/ic_back_white.xml
  app/src/main/res/drawable/ic_habit_fire_darkgray.xml
  app/src/main/res/drawable/ic_habit_fire_default.xml
  app/src/main/res/drawable/ic_habit_sticker_complete.xml
  app/src/main/res/drawable/ic_habit_sticker_rest.xml
  app/src/main/res/drawable/ic_habit_tag_me.xml
  app/src/main/res/drawable/ic_habit_teamlife_empty.xml
  app/src/main/res/drawable/ic_habit_teamlife_white.xml
  app/src/main/res/drawable/ic_more_vertical_white.xml
  app/src/main/res/drawable/layer_list_habit_progressbar.xml
  app/src/main/res/drawable/shape_habit_progress_bar.xml
  app/src/main/res/drawable/shape_habit_progress_bar_bg.xml
  app/src/main/res/drawable/shape_habit_text_box.xml
  app/src/main/res/layout/fragment_habit.xml
  app/src/main/res/layout/item_habit_team.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: 🐉재훈, layout, pull request

#19 #17 [습관방] 습관방 리사이클러뷰 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitFragment.kt
  app/src/main/java/com/spark/android/ui/habit/adapter/HabitRecyclerViewAdapter.kt
  app/src/main/res/drawable-hdpi/btn_today_active.png
  app/src/main/res/drawable-mdpi/btn_today_active.png
  app/src/main/res/drawable-xhdpi/btn_today_active.png
  app/src/main/res/drawable-xxhdpi/btn_today_active.png
  app/src/main/res/drawable-xxxhdpi/btn_today_active.png
  app/src/main/res/layout/activity_habit.xml
  app/src/main/res/layout/fragment_habit.xml
  app/src/main/res/layout/item_habit_team.xml
Labels: 🐉재훈, feat, layout, pull request

#22 #4 [홈_메인] 홈메인 만들기(완료)
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/layout/item_home_recyclerview.xml
  app/src/main/res/values/strings.xml
Labels: 🐷창환, feat, pull request

#24 #23 [습관방] 기타 파일 수정
  app/src/main/res/layout/activity_habit.xml
  app/src/main/res/layout/item_habit_team.xml
  app/src/main/res/values/strings.xml
Labels: 🐉재훈, layout, chore, pull request

#27 #[홈_메인] 플로팅 액션버튼 완료(추가적인 배경관련 리펙토링 필요)
  app/src/main/java/com/spark/android/ui/MainActivity.kt
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
  app/src/main/java/com/spark/android/ui/home/data/TicketData.kt
  app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt
  app/src/main/java/com/spark/android/ui/home/viewmodel/MainViewModel.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/java/com/spark/android/util/FloatingAnimationUtil.kt
  app/src/main/res/drawable/ic_fab_join_code.xml
  app/src/main/res/drawable/ic_fab_make_room.xml
  app/src/main/res/drawable/ic_fab_plus.xml
  app/src/main/res/drawable/ic_fab_plus_rotate_45.xml
  app/src/main/res/layout/fragment_home_main.xml
  app/src/main/res/layout/item_home_recyclerview.xml
  app/src/main/res/layout/item_home_recyclerview_waiting.xml
  app/src/main/res/values/colors.xml
Labels: 🐷창환, feat, layout, pull request

#29 #6 [보관함_메인] 보관함메인 만들기
  app/src/main/drawable-hdpi/bg_linegrid_for_white.png
  app/src/main/drawable-mdpi/bg_linegrid_for_white.png
  app/src/main/drawable-xhdpi/bg_linegrid_for_white.png
  app/src/main/drawable-xxhdpi/bg_linegrid_for_white.png
  app/src/main/drawable-xxxhdpi/bg_linegrid_for_white.png
  app/src/main/java/com/spark/android/ui/MainActivity.kt
  app/src/main/java/com/spark/android/ui/home/StorageFragment.kt
  app/src/main/java/com/spark/android/ui/storage/CompleteVpAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/IncompleteVpAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/ProgressingVpAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/StorageCompleteFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StorageFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StorageIncompleteFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StorageProgressingFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StorageViewPagerOutAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/viewmodel/StorageViewModel.kt
  app/src/main/res/drawable-hdpi/bg_linegrid_for_white.png
  app/src/main/res/drawable-hdpi/ic_storage_complete_item_sparkflake.png
  app/src/main/res/drawable-hdpi/ic_storage_incomplete_item_sparkflake.png
  app/src/main/res/drawable-hdpi/ic_storage_progressing_item_sparkflake.png
  app/src/main/res/drawable-hdpi/img_storage_incomplete_certification_photo.jpg
  app/src/main/res/drawable-hdpi/img_storage_progressing_certification_photo.jpg
  app/src/main/res/drawable-mdpi/bg_linegrid_for_white.png
  app/src/main/res/drawable-mdpi/ic_storage_complete_item_sparkflake.png
  app/src/main/res/drawable-mdpi/ic_storage_incomplete_item_sparkflake.png
  app/src/main/res/drawable-mdpi/ic_storage_progressing_item_sparkflake.png
  app/src/main/res/drawable-xhdpi/bg_linegrid_for_white.png
  app/src/main/res/drawable-xhdpi/ic_storage_complete_item_sparkflake.png
  app/src/main/res/drawable-xhdpi/ic_storage_incomplete_item_sparkflake.png
  app/src/main/res/drawable-xhdpi/ic_storage_progressing_item_sparkflake.png
  app/src/main/res/drawable-xxhdpi/bg_linegrid_for_white.png
  app/src/main/res/drawable-xxhdpi/ic_storage_complete_item_sparkflake.png
  app/src/main/res/drawable-xxhdpi/ic_storage_incomplete_item_sparkflake.png
  app/src/main/res/drawable-xxhdpi/ic_storage_progressing_item_sparkflake.png
  app/src/main/res/drawable-xxxhdpi/bg_linegrid_for_white.png
  app/src/main/res/drawable-xxxhdpi/ic_storage_complete_item_sparkflake.png
  app/src/main/res/drawable-xxxhdpi/ic_storage_incomplete_item_sparkflake.png
  app/src/main/res/drawable-xxxhdpi/ic_storage_progressing_item_sparkflake.png
  app/src/main/res/drawable/bg_storage_black_filter.xml
  app/src/main/res/drawable/ic_storage_complete_deco_left.xml
  app/src/main/res/drawable/ic_storage_complete_deco_right.xml
  app/src/main/res/drawable/img_storage_complete_certification_photo.jpg
  app/src/main/res/drawable/shape_spark_dark_pinkred_fill_line_2_rect.xml
  app/src/main/res/drawable/shape_spark_dark_pinkred_line_2_rect_bottomless.xml
  app/src/main/res/drawable/shape_spark_gray_line_2_rect.xml
  app/src/main/res/drawable/shape_spark_light_pinkred_fill_line_2_rect.xml
  app/src/main/res/drawable/shape_spark_light_pinkred_line_2_rect_bottomless.xml
  app/src/main/res/frame_324.svg
  app/src/main/res/layout/fragment_storage.xml
  app/src/main/res/layout/fragment_storage_complete.xml
  app/src/main/res/layout/fragment_storage_incomplete.xml
  app/src/main/res/layout/fragment_storage_progressing.xml
  app/src/main/res/layout/item_complete_list.xml
  app/src/main/res/layout/item_incomplete_list.xml
  app/src/main/res/layout/item_progressing_list.xml
  app/src/main/res/values/dimen.xml
Labels: 🐬호재, pull request

#31 #30 [layout] 보관함 격자 배경 사이즈 조절 및 카드 모서리 튀어나온 부분 해결
  app/src/main/res/layout/fragment_storage.xml
Labels: 🐬호재, pull request

#33 #15 [피드] 피드화면 디자인 및 구현 (서버 연결 제외)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/data/response/FeedResponse.kt
  app/src/main/java/com/spark/android/ui/MainActivity.kt
  app/src/main/java/com/spark/android/ui/feed/FeedFragment.kt
  app/src/main/java/com/spark/android/ui/feed/FeedViewModel.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedAdapter.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedHeaderDecoration.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedStickyHeaderResolver.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedStickyHeaderResolverImpl.kt
  app/src/main/java/com/spark/android/ui/home/FeedFragment.kt
  app/src/main/java/com/spark/android/ui/profile/ProfileFragment.kt
  app/src/main/java/com/spark/android/ui/signin/SignInFragment.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/drawable-hdpi/ic_feed_fire_gray.png
  app/src/main/res/drawable-mdpi/ic_feed_fire_gray.png
  app/src/main/res/drawable-xhdpi/ic_feed_fire_gray.png
  app/src/main/res/drawable-xxhdpi/ic_feed_fire_gray.png
  app/src/main/res/drawable-xxxhdpi/ic_feed_fire_gray.png
  app/src/main/res/drawable/ic_feed_heart_gray.xml
  app/src/main/res/drawable/ic_feed_heart_pink.xml
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/layout/item_feed_content.xml
  app/src/main/res/layout/item_feed_header.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#37 #36 [layout] MainActivity 탭 간격 수정
  app/src/main/java/com/spark/android/ui/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: 🐷창환, pull request

#38 #28 [홈메인] 바텀네비게이션,홈 리사이클러뷰 디자인관련 오류사항 수정
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_home_recyclerview.xml
Labels: 🐷창환, layout, pull request

#39 #36 [홈_메인] 각버튼 인텐트 추가, fab 백그라운드 클릭 리스너 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/ui/home/adapter/HomeRecyclerViewAdapter.kt
  app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt
  app/src/main/java/com/spark/android/ui/main/MainActivity.kt
  app/src/main/java/com/spark/android/ui/makeroom/MakeRoomActivity.kt
  app/src/main/java/com/spark/android/util/FloatingAnimationUtil.kt
  app/src/main/res/layout/activity_join_code.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_make_room.xml
Labels: 🐷창환, feat, pull request

#41 #26 [습관방] 더보기, 오늘의 인증 구현
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/res/drawable/bg_habit_today_inactive.xml
  app/src/main/res/drawable/ic_habit_today_photo.xml
  app/src/main/res/drawable/ic_habit_today_stopwatch.xml
  app/src/main/res/drawable/shape_bottom_sheet_frame.xml
  app/src/main/res/drawable/shape_btn_active.xml
  app/src/main/res/drawable/shape_habit_today_btn.xml
  app/src/main/res/layout/bottom_sheet_habit_more.xml
  app/src/main/res/layout/bottom_sheet_habit_today.xml
  app/src/main/res/values/styles.xml
Labels: 🐉재훈, feat, layout, pull request

#43 #34 [회원가입] 회원가입 프로필 설정 모든 디자인 구현
  app/src/main/java/com/spark/android/ui/profile/ProfileBottomSheet.kt
  app/src/main/java/com/spark/android/ui/profile/ProfileFragment.kt
  app/src/main/java/com/spark/android/util/DialogUtil.kt
  app/src/main/res/layout/bottom_sheet_profile.xml
  app/src/main/res/layout/dialog_util.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#46 #42 [습관방] 바텀 시트 및 기타 레이아웃 수정
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitMoreBottomSheet.kt
  app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt
  app/src/main/java/com/spark/android/ui/home/adapter/HomeRecyclerViewAdapter.kt
  app/src/main/res/drawable/shape_habit_today_active.xml
  app/src/main/res/drawable/shape_habit_today_inactive.xml
  app/src/main/res/font/futura.xml
  app/src/main/res/font/futura_medium_italic.otf
  app/src/main/res/layout/activity_habit.xml
  app/src/main/res/layout/bottom_sheet_habit_more.xml
  app/src/main/res/layout/bottom_sheet_habit_today.xml
  app/src/main/res/values/styles.xml
Labels: 🐉재훈, feat, layout, chore, pull request

#47 #45 [습관방 생성_방이름 설정] 방이름 설정 프래그먼트 만들기
  app/src/main/java/com/spark/android/ui/makeroom/MakeRoomActivity.kt
  app/src/main/java/com/spark/android/ui/makeroom/namesetting/NameSettingFragment.kt
  app/src/main/java/com/spark/android/ui/makeroom/namesetting/viewmodel/NameSettingViewModel.kt
  app/src/main/res/drawable/ic_make_room_name_setting_back.xml
  app/src/main/res/drawable/shape_btn_inactive.xml
  app/src/main/res/layout/activity_make_room.xml
  app/src/main/res/layout/fragment_name_setting.xml
  app/src/main/res/values/strings.xml
Labels: 🐷창환, feat, layout, pull request

#51 #48 [습관방 생성_인증 방식 선택] 인증 방식 선택 프래그먼트 완료
  app/src/main/java/com/spark/android/ui/makeroom/MakeRoomActivity.kt
  app/src/main/java/com/spark/android/ui/makeroom/namesetting/NameSettingFragment.kt
  app/src/main/java/com/spark/android/ui/makeroom/selectconfirmmethod/SelectConfirmMethodFragment.kt
  app/src/main/java/com/spark/android/ui/makeroom/selectconfirmmethod/viewmodel/SelectConfirmMethodViewModel.kt
  app/src/main/res/drawable-hdpi/img_select_confirm_method_active_photo_sticker.png
  app/src/main/res/drawable-hdpi/img_select_confirm_method_active_stop_watch_sticker.png
  app/src/main/res/drawable-hdpi/img_select_confirm_method_inactive_photo_sticker.png
  app/src/main/res/drawable-hdpi/img_select_confirm_method_inactive_stop_watch_sticker.png
  app/src/main/res/drawable-mdpi/img_select_confirm_method_active_photo_sticker.png
  app/src/main/res/drawable-mdpi/img_select_confirm_method_active_stop_watch_sticker.png
  app/src/main/res/drawable-mdpi/img_select_confirm_method_inactive_photo_sticker.png
  app/src/main/res/drawable-mdpi/img_select_confirm_method_inactive_stop_watch_sticker.png
  app/src/main/res/drawable-xhdpi/img_select_confirm_method_active_photo_sticker.png
  app/src/main/res/drawable-xhdpi/img_select_confirm_method_active_stop_watch_sticker.png
  app/src/main/res/drawable-xhdpi/img_select_confirm_method_inactive_photo_sticker.png
  app/src/main/res/drawable-xhdpi/img_select_confirm_method_inactive_stop_watch_sticker.png
  app/src/main/res/drawable-xxhdpi/img_select_confirm_method_active_photo_sticker.png
  app/src/main/res/drawable-xxhdpi/img_select_confirm_method_active_stop_watch_sticker.png
  app/src/main/res/drawable-xxhdpi/img_select_confirm_method_inactive_photo_sticker.png
  app/src/main/res/drawable-xxhdpi/img_select_confirm_method_inactive_stop_watch_sticker.png
  app/src/main/res/drawable-xxxhdpi/img_select_confirm_method_active_photo_sticker.png
  app/src/main/res/drawable-xxxhdpi/img_select_confirm_method_active_stop_watch_sticker.png
  app/src/main/res/drawable-xxxhdpi/img_select_confirm_method_inactive_photo_sticker.png
  app/src/main/res/drawable-xxxhdpi/img_select_confirm_method_inactive_stop_watch_sticker.png
  app/src/main/res/drawable/ic_make_room_back.xml
  app/src/main/res/drawable/shape_spark_light_gray_line_rect.xml
  app/src/main/res/drawable/shape_spark_most_light_pinkred_fill_line_rect.xml
  app/src/main/res/layout/fragment_name_setting.xml
  app/src/main/res/layout/fragment_select_confirm_method.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🐷창환, feat, layout, pull request

#53 #49 [로그인, 회원가입] 카카오로그인, FCM 푸쉬알림
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/SparkApplication.kt
  app/src/main/java/com/spark/android/SparkMessagingService.kt
  app/src/main/java/com/spark/android/data/repository/SignInRepository.kt
  app/src/main/java/com/spark/android/data/repository/SignInRepositoryImpl.kt
  app/src/main/java/com/spark/android/di/RepositoryModule.kt
  app/src/main/java/com/spark/android/ui/auth/AuthActivity.kt
  app/src/main/java/com/spark/android/ui/feed/FeedViewModel.kt
  app/src/main/java/com/spark/android/ui/intro/IntroActivity.kt
  app/src/main/java/com/spark/android/ui/profile/ProfileFragment.kt
  app/src/main/java/com/spark/android/ui/signin/SignInFragment.kt
  app/src/main/java/com/spark/android/ui/signin/SignInViewModel.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
  build.gradle
  settings.gradle
Labels: 🦁연주, pull request

#57 #52 [대기방] 대기방 프래그먼트 완료
  app/src/main/java/com/spark/android/SparkApplication.kt
  app/src/main/java/com/spark/android/ui/makeroom/MakeRoomActivity.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/adapter/WaitingRoomRecyclerViewAdapter.kt
  app/src/main/java/com/spark/android/ui/waitingroom/data/WaitingData.kt
  app/src/main/java/com/spark/android/ui/waitingroom/viewmodel/WaitingRoomViewModel.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/java/com/spark/android/util/FloatingAnimationUtil.kt
  app/src/main/res/drawable-hdpi/img_waiting_room_edit.png
  app/src/main/res/drawable-hdpi/img_waiting_room_refresh.png
  app/src/main/res/drawable-hdpi/img_waiting_room_tooltip_picture.png
  app/src/main/res/drawable-hdpi/img_waiting_room_tooltip_timer.png
  app/src/main/res/drawable-mdpi/img_waiting_room_edit.png
  app/src/main/res/drawable-mdpi/img_waiting_room_refresh.png
  app/src/main/res/drawable-mdpi/img_waiting_room_tooltip_picture.png
  app/src/main/res/drawable-mdpi/img_waiting_room_tooltip_timer.png
  app/src/main/res/drawable-xhdpi/img_waiting_room_edit.png
  app/src/main/res/drawable-xhdpi/img_waiting_room_refresh.png
  app/src/main/res/drawable-xhdpi/img_waiting_room_tooltip_picture.png
  app/src/main/res/drawable-xhdpi/img_waiting_room_tooltip_timer.png
  app/src/main/res/drawable-xxhdpi/img_waiting_room_edit.png
  app/src/main/res/drawable-xxhdpi/img_waiting_room_refresh.png
  app/src/main/res/drawable-xxhdpi/img_waiting_room_tooltip_picture.png
  app/src/main/res/drawable-xxhdpi/img_waiting_room_tooltip_timer.png
  app/src/main/res/drawable-xxxhdpi/img_waiting_room_edit.png
  app/src/main/res/drawable-xxxhdpi/img_waiting_room_refresh.png
  app/src/main/res/drawable-xxxhdpi/img_waiting_room_tooltip_picture.png
  app/src/main/res/drawable-xxxhdpi/img_waiting_room_tooltip_timer.png
  app/src/main/res/drawable/ic_waiting_room_home.xml
  app/src/main/res/drawable/ic_waiting_room_info.xml
  app/src/main/res/drawable/shape_spark_dark_pinkred_line_rect.xml
  app/src/main/res/drawable/shape_spark_deep_gray_fill_rect.xml
  app/src/main/res/layout/fragment_waiting_room.xml
  app/src/main/res/layout/item_waiting_room_recyclerview.xml
  app/src/main/res/values/strings.xml
Labels: 🐷창환, feat, layout, refactor, pull request

#60 Feature/profile signup
  app/build.gradle
  app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesDataSource.kt
  app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/api/FeedService.kt
  app/src/main/java/com/spark/android/data/remote/datasource/FeedDataSource.kt
  app/src/main/java/com/spark/android/data/remote/datasource/FeedDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/FeedRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/FeedRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/ProfileRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/ProfileRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/SignInRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/SignInRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/response/FeedResponse.kt
  app/src/main/java/com/spark/android/data/repository/SignInRepository.kt
  app/src/main/java/com/spark/android/data/repository/SignInRepositoryImpl.kt
  app/src/main/java/com/spark/android/di/LocalDataSourceModule.kt
  app/src/main/java/com/spark/android/di/LocalPreferencesModule.kt
  app/src/main/java/com/spark/android/di/RemoteDataSourceModule.kt
  app/src/main/java/com/spark/android/di/RepositoryModule.kt
  app/src/main/java/com/spark/android/di/RetrofitModule.kt
  app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt
  app/src/main/java/com/spark/android/ui/feed/FeedViewModel.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedAdapter.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedHeaderDecoration.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedStickyHeaderResolver.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedStickyHeaderResolverImpl.kt
  app/src/main/java/com/spark/android/ui/main/MainActivity.kt
  app/src/main/java/com/spark/android/ui/profile/ProfileFragment.kt
  app/src/main/java/com/spark/android/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/spark/android/ui/signin/SignInFragment.kt
  app/src/main/java/com/spark/android/ui/signin/SignInViewModel.kt
  app/src/main/java/com/spark/android/util/Event.kt
  app/src/main/java/com/spark/android/util/EventObserver.kt
  app/src/main/java/com/spark/android/util/ToastMessageUtil.kt
  app/src/main/res/layout/item_feed_content.xml
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#61 #50 [습관방] 나의 목표 관리 뷰 디자인
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/ui/habit/HabitGoalManageActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitGoalManageViewModel.kt
  app/src/main/java/com/spark/android/ui/habit/HabitMoreBottomSheet.kt
  app/src/main/res/drawable/ic_quit.xml
  app/src/main/res/layout/activity_habit_goal_manage.xml
  app/src/main/res/layout/bottom_sheet_habit_more.xml
Labels: 🐉재훈, feat, layout, chore, pull request

#63 #54 [fix] 카카오계정 로그인 제외 카카오톡 로그인 context 에러 해결
  app/src/main/java/com/spark/android/SparkApplication.kt
  app/src/main/java/com/spark/android/data/remote/api/FeedService.kt
  app/src/main/java/com/spark/android/data/remote/datasource/FeedDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/SignInRepository.kt
  app/src/main/java/com/spark/android/data/remote/service/FeedService.kt
  app/src/main/java/com/spark/android/di/RemoteDataSourceModule.kt
  app/src/main/java/com/spark/android/di/RepositoryModule.kt
  app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt
  app/src/main/java/com/spark/android/ui/signin/SignInFragment.kt
  app/src/main/java/com/spark/android/ui/signin/SignInViewModel.kt
  app/src/main/res/layout/fragment_sign_in.xml
Labels: 🦁연주, pull request

#64 #54 [feat] KakaoLoginService 생성
  app/src/main/java/com/spark/android/data/remote/service/KakaoLoginService.kt
Labels: 🦁연주, pull request

#65 #58 [방입장_코드 입력] 다이얼로그 프래그먼트 만들기
  app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt
  app/src/main/java/com/spark/android/ui/joincode/inputcode/InputCodeFragmentDialog.kt
  app/src/main/java/com/spark/android/ui/joincode/inputcode/viewModel/InputCodeFragmnetDialogViewModel.kt
  app/src/main/java/com/spark/android/ui/main/MainActivity.kt
  app/src/main/java/com/spark/android/ui/makeroom/MakeRoomActivity.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/drawable/shape_spark_white_fill_2_rect.xml
  app/src/main/res/layout/activity_join_code.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_input_code_dialog.xml
  app/src/main/res/layout/fragment_name_setting.xml
  app/src/main/res/layout/fragment_select_confirm_method.xml
  app/src/main/res/layout/fragment_waiting_room.xml
  app/src/main/res/values/strings.xml
Labels: 🐷창환, feat, pull request

#68 #62 [습관방] 스파크 보내기
  app/src/main/java/com/spark/android/ui/habit/HabitSendSparkBottomSheet.kt
  app/src/main/java/com/spark/android/ui/habit/adapter/HabitRecyclerViewAdapter.kt
  app/src/main/java/com/spark/android/util/SendSparkToast.kt
  app/src/main/res/drawable/ic_habit_send_spark_hand.xml
  app/src/main/res/drawable/shape_habit_send_spark_toast_box.xml
  app/src/main/res/layout/bottom_sheet_habit_send_spark.xml
  app/src/main/res/layout/toast_habit_send_spark_complete.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🐉재훈, feat, layout, chore, pull request

#70 #69 [습관방] 모든 Button 변경, strings.xml 외 기타 파일 수정
  app/src/main/res/layout/activity_habit.xml
  app/src/main/res/layout/activity_habit_goal_manage.xml
  app/src/main/res/layout/bottom_sheet_habit_more.xml
  app/src/main/res/layout/bottom_sheet_habit_today.xml
  app/src/main/res/layout/item_habit_team.xml
  app/src/main/res/layout/toast_habit_send_spark_complete.xml
  app/src/main/res/values/strings.xml
Labels: 🐉재훈, layout, chore

#71 #56 [타이머] 타이머 인증 액티비티 뷰 만들기
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt
  app/src/main/java/com/spark/android/ui/timer/viewmodel/TimerStartViewModel.kt
  app/src/main/res/drawable/ic_timer_stopwatch_pause.xml
  app/src/main/res/drawable/ic_timer_stopwatch_play.xml
  app/src/main/res/drawable/ic_timer_stopwatch_stop.xml
  app/src/main/res/drawable/shape_spark_dark_pinkred_fill_2_rect.xml
  app/src/main/res/layout/activity_storage_photo_collection.xml
  app/src/main/res/layout/activity_timer_start.xml
  app/src/main/res/layout/item_photo_collection_list.xml
  app/src/main/res/values/strings.xml
Labels: pull request

#76 Feature/timer dialog
  app/src/main/res/ic_quit.svg
  app/src/main/res/layout/activity_timer_start.xml
Labels: 🐬호재, pull request

#81 #59 [로그인, 회원가입] 카카오 로그인 후 프로필 입력하여 회원가입 구현 후 토큰 로컬에 저장 (프로필 사진 입력 제외)
  app/src/main/java/com/spark/android/data/remote/datasource/AuthDataSource.kt
  app/src/main/java/com/spark/android/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/entity/request/SignUpRequest.kt
  app/src/main/java/com/spark/android/data/remote/entity/response/FeedResponse.kt
  app/src/main/java/com/spark/android/data/remote/entity/response/SignUpResponse.kt
  app/src/main/java/com/spark/android/data/remote/repository/AuthRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/ProfileRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/ProfileRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/AuthService.kt
  app/src/main/java/com/spark/android/di/RemoteDataSourceModule.kt
  app/src/main/java/com/spark/android/di/RepositoryModule.kt
  app/src/main/java/com/spark/android/di/RetrofitModule.kt
  app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt
  app/src/main/java/com/spark/android/ui/feed/FeedViewModel.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedAdapter.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedHeaderDecoration.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedStickyHeaderResolver.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedStickyHeaderResolverImpl.kt
  app/src/main/java/com/spark/android/ui/profile/ProfileFragment.kt
  app/src/main/java/com/spark/android/ui/profile/ProfileViewModel.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_feed_content.xml
Labels: 🦁연주, pull request

#83 #82 [feat] Hilt 안 쓸 경우 사용할 서버통신 소스 구현
  app/src/main/java/com/spark/android/SparkApplication.kt
  app/src/main/java/com/spark/android/data/remote/LocalPreferences.kt
  app/src/main/java/com/spark/android/data/remote/RetrofitBuilder.kt
Labels: 🦁연주, pull request

#87 #77 [오늘의 인증] 인증하기 뷰 디자인
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt
  app/src/main/java/com/spark/android/ui/certify/CertifyBottomSheet.kt
  app/src/main/java/com/spark/android/ui/certify/viewmodel/CertifyViewModel.kt
  app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt
  app/src/main/res/drawable/ic_logo_black.xml
  app/src/main/res/drawable/shape_spark_dark_pinkred_line_2_rect.xml
  app/src/main/res/drawable/shape_spark_light_gray_fill_rect.xml
  app/src/main/res/layout/activity_certify.xml
  app/src/main/res/layout/bottom_sheet_certify.xml
  app/src/main/res/layout/toast_habit_send_spark_complete.xml
  app/src/main/res/values/strings.xml
Labels: 🐉재훈, feat, layout, chore, pull request

#89 #88 [오늘의 인증] 액티비티 연결 및 다이얼로그 설정
  app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt
  app/src/main/java/com/spark/android/ui/home/adapter/HomeRecyclerViewAdapter.kt
  app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt
  app/src/main/java/com/spark/android/util/DialogUtil.kt
  app/src/main/res/layout/activity_timer_start.xml
  app/src/main/res/values/strings.xml
Labels: 🐉재훈, feat, layout, chore, pull request

#90 #86 [타이머] x버튼, 뒤로가기 버튼, 다이얼로그 붙임
  app/src/main/java/com/spark/android/data/remote/service/StorageService.kt
  app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt
Labels: pull request

#92 #91 [타이머] 타이머 종료버튼 터치영역 늘림
  app/src/main/res/layout/activity_timer_start.xml
Labels: layout

#94 #84 [회원가입] 프로필 사진 설정 후 회원가입 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/ui/auth/profile/MultiPartResolver.kt
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileBottomSheet.kt
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileFragment.kt
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileViewModel.kt
  app/src/main/java/com/spark/android/ui/auth/signin/SignInFragment.kt
  app/src/main/java/com/spark/android/ui/auth/signin/SignInViewModel.kt
  app/src/main/java/com/spark/android/ui/profile/ProfileBottomSheet.kt
  app/src/main/java/com/spark/android/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/layout/bottom_sheet_profile.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/navigation/auth_nav_graph.xml
Labels: 🦁연주, pull request

#95 #80 [홈_메인] 홈화면 네트워크 붙이기
  app/src/main/java/com/spark/android/data/remote/entity/response/BaseResponse.kt
  app/src/main/java/com/spark/android/data/remote/entity/response/HomeResponse.kt
  app/src/main/java/com/spark/android/data/remote/repository/HomeRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/HomeService.kt
  app/src/main/java/com/spark/android/di/RepositoryModule.kt
  app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
  app/src/main/java/com/spark/android/ui/home/adapter/HomeRecyclerViewAdapter.kt
  app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/layout/fragment_home_main.xml
  app/src/main/res/layout/item_home_recyclerview.xml
  app/src/main/res/layout/item_home_recyclerview_waiting.xml
  app/src/main/res/values/strings.xml
Labels: 🐷창환, feat, layout, pull request

#97 #96 [chore] 보관함 색깔별로 아이템 추가하기, 아이템 테두리 파일 이름 리네임 함
  app/src/main/res/drawable/shape_spark_bright_pinkred_fill_line_rect_2_black.xml
  app/src/main/res/drawable/shape_spark_bright_pinkred_line_2_rect_bottomless.xml
  app/src/main/res/drawable/shape_spark_dark_pinkred_fill_line_2_rect_black.xml
  app/src/main/res/drawable/shape_spark_gray_fill_line_2_rect_black.xml
  app/src/main/res/drawable/shape_spark_light_pinkred_fill_line_2_rect_black.xml
  app/src/main/res/drawable/shape_spark_more_light_pinkred_fill_line_2_rect_black.xml
  app/src/main/res/drawable/shape_spark_more_light_pinkred_line_2_rect_bottomless.xml
  app/src/main/res/drawable/shape_spark_most_light_pinkred_fill_line_2_rect_black.xml
  app/src/main/res/drawable/shape_spark_most_light_pinkred_line_2_rect_bottomless.xml
  app/src/main/res/drawable/shape_spark_pinkred_fill_line_2_rect_black.xml
  app/src/main/res/drawable/shape_spark_pinkred_line_2_rect_bottomless.xml
  app/src/main/res/layout/item_complete_list.xml
  app/src/main/res/layout/item_incomplete_list.xml
  app/src/main/res/layout/item_progressing_list.xml
Labels: pull request

#100 #93 [오늘의 인증] 인증하기 뷰 레이아웃, 버튼 수정
  app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt
  app/src/main/java/com/spark/android/ui/certify/CertifyMode.kt
  app/src/main/java/com/spark/android/ui/certify/viewmodel/CertifyViewModel.kt
  app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt
  app/src/main/java/com/spark/android/util/DialogUtil.kt
  app/src/main/res/layout/activity_certify.xml
  app/src/main/res/layout/activity_habit.xml
  app/src/main/res/layout/activity_habit_goal_manage.xml
  app/src/main/res/layout/bottom_sheet_habit_today.xml
  app/src/main/res/values/strings.xml
Labels: 🐉재훈, feat, layout, chore, pull request

#103 #102 [방 생성] 습관방 생성 네트워크 붙이기 완료
  app/src/main/java/com/spark/android/data/remote/entity/request/MakeRoomRequest.kt
  app/src/main/java/com/spark/android/data/remote/entity/response/MakeRoomResponse.kt
  app/src/main/java/com/spark/android/data/remote/repository/MakeRoomRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/MakeRoomRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/MakeRoomService.kt
  app/src/main/java/com/spark/android/di/RepositoryModule.kt
  app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
  app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt
  app/src/main/java/com/spark/android/ui/main/MainActivity.kt
  app/src/main/java/com/spark/android/ui/makeroom/MakeRoomActivity.kt
  app/src/main/java/com/spark/android/ui/makeroom/selectconfirmmethod/SelectConfirmMethodFragment.kt
  app/src/main/java/com/spark/android/ui/makeroom/selectconfirmmethod/viewmodel/SelectConfirmMethodViewModel.kt
  app/src/main/java/com/spark/android/util/FloatingAnimationUtil.kt
  app/src/main/res/layout/item_home_recyclerview.xml
  app/src/main/res/layout/item_home_recyclerview_waiting.xml
  app/src/main/res/values/strings.xml
Labels: 🐷창환, feat, pull request

#105 #101 [오늘의 인증] 사진 촬영, 앨범에서 가져오기 기능 구현
  app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt
  app/src/main/java/com/spark/android/ui/certify/CertifyBottomSheet.kt
  app/src/main/java/com/spark/android/ui/certify/viewmodel/CertifyViewModel.kt
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/java/com/spark/android/util/DialogUtil.kt
  app/src/main/res/layout/activity_certify.xml
  app/src/main/res/layout/bottom_sheet_habit_today.xml
  app/src/main/res/values/strings.xml
Labels: 🐉재훈, feat, layout, chore, pull request

#106 #98 [feat] 사진인증에서 뒤로가면 타이머 일시정지 유지
  app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitGoalManageActivity.kt
  app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt
Labels: feat, chore

#107 #99 [스플래시] 스플래시 로티 적용하기
  app/src/main/assets/splash.json
  app/src/main/java/com/spark/android/ui/auth/profile/MultiPartResolver.kt
  app/src/main/java/com/spark/android/ui/intro/IntroActivity.kt
  app/src/main/java/com/spark/android/ui/intro/IntroViewModel.kt
  app/src/main/res/layout/activity_intro.xml
Labels: 🦁연주, pull request

#109 #108 [modify] 인증화면 코드 수정
  app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt
Labels: 🐬호재, modify

#111 #110 [오늘의 인증] 타이머-사진 인증 연결 수정
  app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt
  app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt
Labels: 🐉재훈, feat, layout, chore

#115 #113 [습관방, 오늘의 인증] 레이아웃 색 변경 및 타이머 버튼 위치 조정
  app/src/main/res/layout/activity_timer_start.xml
  app/src/main/res/layout/bottom_sheet_certify.xml
  app/src/main/res/layout/bottom_sheet_habit_more.xml
  app/src/main/res/layout/bottom_sheet_habit_send_spark.xml
  app/src/main/res/layout/bottom_sheet_habit_today.xml
  app/src/main/res/layout/item_habit_team.xml
Labels: feat, layout, pull request

#120 #119 [대기방] 인원 목록 새로고침 네트워크 붙였으니 500오류남 (추후 수정)
  app/src/main/java/com/spark/android/data/remote/entity/response/RefreshResponse.kt
  app/src/main/java/com/spark/android/data/remote/repository/RefreshRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/RefreshRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/RefreshService.kt
  app/src/main/java/com/spark/android/di/RepositoryModule.kt
  app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/viewmodel/WaitingRoomViewModel.kt
Labels: 🐷창환, feat, pull request

#122 #121 [대기방] 습관방 시작 네트워크 붙였으나 500 오류(추후 수정)
  app/src/main/java/com/spark/android/data/remote/entity/response/NoDataResponse.kt
  app/src/main/java/com/spark/android/data/remote/repository/SetPurposeRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/SetPurposeRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/StartHabitRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/StartHabitRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/SetPurposeService.kt
  app/src/main/java/com/spark/android/data/remote/service/StartHabitService.kt
  app/src/main/java/com/spark/android/di/RepositoryModule.kt
  app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt
  app/src/main/java/com/spark/android/ui/home/adapter/HomeRecyclerViewAdapter.kt
  app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/viewmodel/WaitingRoomViewModel.kt
Labels: 🐷창환, feat, pull request

#125 #124 [전체화면] 기타 오류 및 액티비티간 이동 관계정리, 애니메이션 처리
  app/src/main/java/com/spark/android/ui/home/adapter/HomeRecyclerViewAdapter.kt
  app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt
  app/src/main/java/com/spark/android/ui/joincode/inputcode/InputCodeFragmentDialog.kt
  app/src/main/java/com/spark/android/ui/makeroom/selectconfirmmethod/SelectConfirmMethodFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomActivity.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/java/com/spark/android/util/FloatingAnimationUtil.kt
  app/src/main/res/layout/fragment_input_code_dialog.xml
  app/src/main/res/layout/fragment_waiting_room.xml
Labels: 🐷창환, feat, pull request

#127 #123 [습관방 입장] 코드로 대기방 정보확인 네트워크 붙이기
  app/build.gradle
  app/src/main/java/com/spark/android/data/remote/entity/response/JoinCodeRoomInfoResponse.kt
  app/src/main/java/com/spark/android/data/remote/repository/JoinCodeRoomInfoRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/JoinCodeRoomInfoRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/JoinCodeRoomInfoService.kt
  app/src/main/java/com/spark/android/di/RepositoryModule.kt
  app/src/main/java/com/spark/android/di/RetrofitModule.kt
  app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt
  app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt
  app/src/main/java/com/spark/android/ui/joincode/inputcode/InputCodeFragmentDialog.kt
  app/src/main/java/com/spark/android/ui/joincode/inputcode/viewModel/InputCodeFragmnetDialogViewModel.kt
  app/src/main/res/layout/activity_join_code.xml
Labels: 🐷창환, feat, pull request

#128 #126 [대기방] 새로고침 중복터치 막기
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/java/com/spark/android/util/FloatingAnimationUtil.kt
Labels: 🐷창환, feat, pull request

#129 #112 [보관함] 보관함 서버 붙이기
  app/src/main/AndroidManifest.xml
  app/src/main/drawable-hdpi/bg_linegrid_for_white.png
  app/src/main/drawable-mdpi/bg_linegrid_for_white.png
  app/src/main/drawable-xhdpi/bg_linegrid_for_white.png
  app/src/main/drawable-xxhdpi/bg_linegrid_for_white.png
  app/src/main/drawable-xxxhdpi/bg_linegrid_for_white.png
  app/src/main/java/com/spark/android/data/remote/RetrofitBuilder.kt
  app/src/main/java/com/spark/android/data/remote/entity/response/StorageResponse.kt
  app/src/main/java/com/spark/android/data/remote/service/StorageService.kt
  app/src/main/java/com/spark/android/ui/storage/StorageCompleteFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StorageFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StorageIncompleteFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StorageMode.kt
  app/src/main/java/com/spark/android/ui/storage/StorageProgressingFragment.kt
  app/src/main/java/com/spark/android/ui/storage/adapter/CompleteVpAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/adapter/IncompleteVpAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/adapter/ProgressingVpAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/viewmodel/StorageViewModel.kt
  app/src/main/res/layout/fragment_storage.xml
  app/src/main/res/layout/item_storage_complete_list.xml
  app/src/main/res/layout/item_storage_incomplete_list.xml
  app/src/main/res/layout/item_storage_progressing_list.xml
Labels: 🐬호재, pull request

#131 #114 [피드] 피드 서버 연결 및 무한스크롤 구현
  app/build.gradle
  app/src/main/assets/loading.json
  app/src/main/java/com/spark/android/data/remote/datasource/AuthDataSource.kt
  app/src/main/java/com/spark/android/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/datasource/FeedDataSource.kt
  app/src/main/java/com/spark/android/data/remote/datasource/FeedDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/entity/response/BaseResponse.kt
  app/src/main/java/com/spark/android/data/remote/entity/response/FeedResponse.kt
  app/src/main/java/com/spark/android/data/remote/entity/response/SignUpResponse.kt
  app/src/main/java/com/spark/android/data/remote/repository/AuthRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/FeedRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/FeedRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/AuthService.kt
  app/src/main/java/com/spark/android/data/remote/service/FeedService.kt
  app/src/main/java/com/spark/android/di/RepositoryModule.kt
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileFragment.kt
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileViewModel.kt
  app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt
  app/src/main/java/com/spark/android/ui/feed/FeedFragment.kt
  app/src/main/java/com/spark/android/ui/feed/FeedPagingSource.kt
  app/src/main/java/com/spark/android/ui/feed/FeedViewModel.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedAdapter.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedHeaderDecoration.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedStickyHeaderResolver.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedStickyHeaderResolverImpl.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/java/com/spark/android/util/MultiPartResolver.kt
  app/src/main/res/drawable/ic_feed_empty.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_feed_content.xml
  app/src/main/res/layout/item_feed_footer.xml
  app/src/main/res/layout/item_feed_loading.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: 🦁연주, pull request

#133 #130 [보관함] 보관함 미완료 카드 에러 수정
  app/src/main/java/com/spark/android/data/remote/entity/response/StorageResponse.kt
Labels: 🐬호재, pull request

#134 #118 [습관방] 특정 습관방 상세조회 서버 연결
  app/src/main/java/com/spark/android/data/remote/RetrofitBuilder.kt
  app/src/main/java/com/spark/android/data/remote/entity/response/HabitResponse.kt
  app/src/main/java/com/spark/android/data/remote/service/HabitService.kt
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitGoalManageActivity.kt
  app/src/main/java/com/spark/android/ui/habit/adapter/HabitRecyclerViewAdapter.kt
  app/src/main/java/com/spark/android/ui/habit/viewmodel/HabitGoalManageViewModel.kt
  app/src/main/java/com/spark/android/ui/habit/viewmodel/HabitViewModel.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/drawable/ic_habit_fire_inactive.xml
  app/src/main/res/drawable/ic_habit_sticker_thinking.xml
  app/src/main/res/drawable/layer_list_habit_progressbar_1.xml
  app/src/main/res/drawable/layer_list_habit_progressbar_2.xml
  app/src/main/res/drawable/layer_list_habit_progressbar_3.xml
  app/src/main/res/drawable/layer_list_habit_progressbar_4.xml
  app/src/main/res/drawable/layer_list_habit_progressbar_5.xml
  app/src/main/res/drawable/layer_list_habit_progressbar_6.xml
  app/src/main/res/drawable/layer_list_habit_progressbar_7.xml
  app/src/main/res/drawable/shape_habit_progress_bar.xml
  app/src/main/res/layout/activity_habit.xml
  app/src/main/res/layout/activity_habit_goal_manage.xml
  app/src/main/res/layout/item_habit_team.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🐉재훈, feat, layout, fix, chore, pull request

#137 #136 [습관방 입장] 습관방 참여 완료
  app/src/main/java/com/spark/android/data/remote/repository/JoinCodeRoomDoneRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/JoinCodeRoomDoneRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/JoinCodeRoomDoneService.kt
  app/src/main/java/com/spark/android/di/RepositoryModule.kt
  app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt
  app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt
  app/src/main/java/com/spark/android/ui/joincode/data/JoinCodeData.kt
  app/src/main/java/com/spark/android/ui/joincode/viewmodel/JoinCodeViewModel.kt
Labels: 🐷창환, feat, pull request

#140 #139 [피드] 좋아요 버튼 서버 연결 및 로티 적용
  app/src/main/assets/heart.json
  app/src/main/java/com/spark/android/data/remote/datasource/FeedDataSource.kt
  app/src/main/java/com/spark/android/data/remote/datasource/FeedDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/entity/response/FeedResponse.kt
  app/src/main/java/com/spark/android/data/remote/repository/FeedRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/FeedRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/FeedService.kt
  app/src/main/java/com/spark/android/ui/feed/FeedFragment.kt
  app/src/main/java/com/spark/android/ui/feed/FeedViewModel.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedAdapter.kt
  app/src/main/res/drawable/ic_feed_heart_pink.xml
  app/src/main/res/layout/item_feed_content.xml
Labels: 🦁연주, pull request

#143 #138 [전체화면] 버튼 터치영역 늘리기,홈뷰 탭후 처리, 새로고침 최신화 시키기
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/res/layout/activity_join_code.xml
  app/src/main/res/layout/fragment_name_setting.xml
  app/src/main/res/layout/fragment_select_confirm_method.xml
  app/src/main/res/layout/fragment_set_purpose.xml
  app/src/main/res/layout/fragment_waiting_room.xml
Labels: 🐷창환, feat, pull request

#144 #141 [modify] 메인 화면 네비게이션으로 수정
  app/src/main/java/com/spark/android/ui/main/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/navigation/main_nav_graph.xml
Labels: 🦁연주, pull request

#146 #142 [인증사진] 인증사진 모음 서버 붙이기
  app/src/main/java/com/spark/android/data/remote/RetrofitBuilder.kt
  app/src/main/java/com/spark/android/data/remote/entity/response/PhotoCollectionResponse.kt
  app/src/main/java/com/spark/android/data/remote/service/PhotoCollectionService.kt
  app/src/main/java/com/spark/android/ui/storage/StorageCompleteFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StorageIncompleteFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StoragePhotoCollectionActivity.kt
  app/src/main/java/com/spark/android/ui/storage/StorageProgressingFragment.kt
  app/src/main/java/com/spark/android/ui/storage/adapter/PhotoCollectionRvAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/viewmodel/PhotoCollectionViewModel.kt
  app/src/main/res/layout/activity_storage_photo_collection.xml
  app/src/main/res/layout/item_photo_collection_list.xml
Labels: 🐬호재, pull request

#149 #145 [로그인,회원가입] 회원여부 판별 서버 연결
  app/src/main/java/com/spark/android/data/remote/datasource/AuthDataSource.kt
  app/src/main/java/com/spark/android/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/entity/response/DoorbellResponse.kt
  app/src/main/java/com/spark/android/data/remote/repository/AuthRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/AuthService.kt
  app/src/main/java/com/spark/android/ui/auth/signin/SignInFragment.kt
  app/src/main/java/com/spark/android/ui/auth/signin/SignInViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#151 #135 [습관방] 상태 변경, 스파크 보내기 서버 연결
  app/src/main/java/com/spark/android/data/remote/RetrofitBuilder.kt
  app/src/main/java/com/spark/android/data/remote/entity/request/SendSparkRequest.kt
  app/src/main/java/com/spark/android/data/remote/entity/request/SetStatusRequest.kt
  app/src/main/java/com/spark/android/data/remote/service/SendSparkService.kt
  app/src/main/java/com/spark/android/data/remote/service/SetStatusService.kt
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitSendSparkBottomSheet.kt
  app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt
  app/src/main/java/com/spark/android/ui/habit/adapter/HabitRecyclerViewAdapter.kt
  app/src/main/java/com/spark/android/ui/habit/viewmodel/HabitViewModel.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/java/com/spark/android/util/SendSparkToast.kt
  app/src/main/res/layout/bottom_sheet_habit_send_spark.xml
  app/src/main/res/layout/bottom_sheet_habit_today.xml
  app/src/main/res/layout/item_habit_team.xml
  app/src/main/res/layout/toast_habit_send_spark_complete.xml
Labels: 🐉재훈, pull request

#154 #145 [메인] 네비게이션 적용 부분 백스택 관리 및 앱종료 이벤트 설정
  app/src/main/java/com/spark/android/ui/main/MainActivity.kt
  app/src/main/java/com/spark/android/util/ToastMessageUtil.kt
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#158 #157 [홈_메인] 홈화면 empty view 위치조정 + 글씨 분기처리 조정
  app/src/main/res/layout/fragment_home_main.xml
  app/src/main/res/layout/item_home_recyclerview.xml
Labels: 🐷창환, feat, layout, pull request

#160 #159 [오늘의 인증] 오늘의 인증 서버 연결
  app/src/main/java/com/spark/android/data/remote/entity/request/CertifyRequest.kt
  app/src/main/java/com/spark/android/data/remote/service/CertifyService.kt
  app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt
  app/src/main/java/com/spark/android/ui/certify/viewmodel/CertifyViewModel.kt
Labels: 🐉재훈, pull request

#162 #153 [홈_메인] 로딩 화면 붙이기
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
  app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt
  app/src/main/res/layout/fragment_home_main.xml
Labels: 🐷창환, feat, pull request

#165 #164 [나의 목표 관리] 나의 목표 관리 서버 연결
  app/src/main/java/com/spark/android/data/remote/RetrofitBuilder.kt
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitGoalManageActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitMoreBottomSheet.kt
  app/src/main/java/com/spark/android/ui/habit/viewmodel/HabitGoalManageViewModel.kt
  app/src/main/res/layout/activity_habit_goal_manage.xml
  app/src/main/res/values/strings.xml
Labels: 🐉재훈, pull request

#168 #166 [오늘의 인증] 사진 인증 모드 구현
  app/src/main/java/com/spark/android/data/remote/service/CertifyService.kt
  app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt
  app/src/main/java/com/spark/android/ui/certify/CertifyBottomSheet.kt
  app/src/main/java/com/spark/android/ui/certify/viewmodel/CertifyViewModel.kt
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt
  app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt
Labels: 🐉재훈, pull request

#169 #167 [전체화면] 서버 에러처리 (kotlin runcatching)
  app/src/main/java/com/spark/android/data/remote/repository/HomeRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/JoinCodeRoomDoneRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/JoinCodeRoomDoneRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/MakeRoomRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/MakeRoomRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/RefreshRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/RefreshRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/SetPurposeRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/SetPurposeRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/StartHabitRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/StartHabitRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/WaitingRoomInfoRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/WaitingRoomInfoRepositoryImpl.kt
  app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt
  app/src/main/java/com/spark/android/ui/joincode/viewmodel/JoinCodeViewModel.kt
  app/src/main/java/com/spark/android/ui/makeroom/selectconfirmmethod/viewmodel/SelectConfirmMethodViewModel.kt
  app/src/main/java/com/spark/android/ui/setpurpose/viewmodel/SetPurposeViewModel.kt
  app/src/main/java/com/spark/android/ui/waitingroom/viewmodel/WaitingRoomViewModel.kt
Labels: 🐷창환, refactor

#170 #155 [인스타 공유하기] 습관 인증 후 인스타 공유하기
  app/src/main/AndroidManifest.xml
  app/src/main/assets/insta.json
  app/src/main/assets/splash.json
  app/src/main/assets/splash_bg.json
  app/src/main/assets/splash_logo.json
  app/src/main/java/com/spark/android/data/remote/repository/FeedRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/FeedRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/CertifyService.kt
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileBottomSheet.kt
  app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt
  app/src/main/java/com/spark/android/ui/certify/viewmodel/CertifyViewModel.kt
  app/src/main/java/com/spark/android/ui/feed/FeedFragment.kt
  app/src/main/java/com/spark/android/ui/feed/FeedViewModel.kt
  app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt
  app/src/main/java/com/spark/android/ui/intro/IntroActivity.kt
  app/src/main/java/com/spark/android/ui/main/MainActivity.kt
  app/src/main/java/com/spark/android/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/spark/android/ui/share/InstaActivity.kt
  app/src/main/java/com/spark/android/ui/share/InstaShareDialogFragment.kt
  app/src/main/res/drawable-hdpi/asset_insta_sticker_tag.png
  app/src/main/res/drawable-hdpi/bg_insta_dialog.png
  app/src/main/res/drawable-hdpi/ic_insta_clap.png
  app/src/main/res/drawable-mdpi/asset_insta_sticker_tag.png
  app/src/main/res/drawable-mdpi/bg_insta_dialog.png
  app/src/main/res/drawable-mdpi/ic_insta_clap.png
  app/src/main/res/drawable-xhdpi/asset_insta_sticker_tag.png
  app/src/main/res/drawable-xhdpi/bg_insta_dialog.png
  app/src/main/res/drawable-xhdpi/ic_insta_clap.png
  app/src/main/res/drawable-xxhdpi/asset_insta_sticker_tag.png
  app/src/main/res/drawable-xxhdpi/bg_insta_dialog.png
  app/src/main/res/drawable-xxhdpi/ic_insta_clap.png
  app/src/main/res/drawable-xxxhdpi/asset_insta_sticker_tag.png
  app/src/main/res/drawable-xxxhdpi/bg_insta_dialog.png
  app/src/main/res/drawable-xxxhdpi/ic_insta_clap.png
  app/src/main/res/drawable/ic_instagram.xml
  app/src/main/res/drawable/shape_insta_black_fiil_2.xml
  app/src/main/res/layout/activity_insta.xml
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/dialog_insta_share.xml
  app/src/main/res/layout/item_feed_content.xml
  app/src/main/res/layout/item_home_recyclerview.xml
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#173 #172 [전체화면] 스테이터스 바 색상 변경
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
  app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt
  app/src/main/java/com/spark/android/ui/makeroom/MakeRoomActivity.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomActivity.kt
Labels: 🐷창환, feat

#174 #171 [인증, 인스타 공유] 타이머 없는 인증 관련 에러 수정 및 인스타 공유 연결
  app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt
  app/src/main/java/com/spark/android/ui/certify/CertifyBottomSheet.kt
  app/src/main/java/com/spark/android/ui/certify/viewmodel/CertifyViewModel.kt
  app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt
  app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#176 #175 [인증사진 모아보기] 인증사진 REST, DONE 구현
  app/src/main/java/com/spark/android/ui/storage/StorageFragment.kt
  app/src/main/java/com/spark/android/ui/storage/viewmodel/StorageViewModel.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/drawable-hdpi/ic_sticker_none.png
  app/src/main/res/drawable-hdpi/ic_sticker_rest.png
  app/src/main/res/drawable-mdpi/ic_sticker_none.png
  app/src/main/res/drawable-mdpi/ic_sticker_rest.png
  app/src/main/res/drawable-xhdpi/ic_sticker_none.png
  app/src/main/res/drawable-xhdpi/ic_sticker_rest.png
  app/src/main/res/drawable-xxhdpi/ic_sticker_none.png
  app/src/main/res/drawable-xxhdpi/ic_sticker_rest.png
  app/src/main/res/drawable-xxxhdpi/ic_sticker_none.png
  app/src/main/res/drawable-xxxhdpi/ic_sticker_rest.png
  app/src/main/res/drawable/shape_transparent_2.xml
  app/src/main/res/frame_324.svg
  app/src/main/res/ic_quit.svg
  app/src/main/res/layout/activity_storage_photo_collection.xml
  app/src/main/res/layout/item_photo_collection_list.xml
Labels: 🐬호재, pull request

#178 #177 [layout] item_photo_collection_list.xml rest 스티커 에셋 추가함
  app/src/main/res/drawable-hdpi/sticker_rest.png
  app/src/main/res/drawable-mdpi/sticker_rest.png
  app/src/main/res/drawable-xhdpi/sticker_rest.png
  app/src/main/res/drawable-xxhdpi/sticker_rest.png
  app/src/main/res/drawable-xxxhdpi/sticker_rest.png
Labels: pull request

#181 #180 [습관방] 습관방 수정
  app/src/main/java/com/spark/android/ui/habit/HabitGoalManageActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitSendSparkBottomSheet.kt
  app/src/main/java/com/spark/android/ui/habit/viewmodel/HabitViewModel.kt
  app/src/main/java/com/spark/android/util/SendSparkToast.kt
  app/src/main/res/layout/activity_habit.xml
  app/src/main/res/layout/activity_habit_goal_manage.xml
  app/src/main/res/layout/bottom_sheet_habit_send_spark.xml
Labels: 🐉재훈, pull request

#182 #179 [전체화면] 포커스시 edit text 색상 바꾸기
  app/src/main/java/com/spark/android/ui/habit/HabitGoalManageActivity.kt
  app/src/main/java/com/spark/android/ui/makeroom/namesetting/NameSettingFragment.kt
  app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt
  app/src/main/java/com/spark/android/util/EditTextUtil.kt
Labels: 🐷창환, feat

#183 #171 [전체] 에러 수정
  app/src/main/java/com/spark/android/data/remote/LocalPreferences.kt
  app/src/main/java/com/spark/android/di/LocalPreferencesModule.kt
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileFragment.kt
Labels: 🦁연주, pull request

#185 #184 [QA] 데모데이 전 수정사항
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileViewModel.kt
  app/src/main/java/com/spark/android/ui/certify/viewmodel/CertifyViewModel.kt
  app/src/main/java/com/spark/android/ui/habit/viewmodel/HabitViewModel.kt
  app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt
  app/src/main/java/com/spark/android/ui/joincode/inputcode/InputCodeFragmentDialog.kt
  app/src/main/java/com/spark/android/ui/joincode/inputcode/viewModel/InputCodeFragmnetDialogViewModel.kt
  app/src/main/java/com/spark/android/ui/main/MainActivity.kt
  app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StorageFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StorageIncompleteFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StoragePhotoCollectionActivity.kt
  app/src/main/java/com/spark/android/ui/storage/StorageProgressingFragment.kt
  app/src/main/java/com/spark/android/ui/storage/adapter/CompleteVpAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/adapter/IncompleteVpAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/adapter/ProgressingVpAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/viewmodel/PhotoCollectionViewModel.kt
  app/src/main/java/com/spark/android/ui/storage/viewmodel/StorageViewModel.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/viewmodel/WaitingRoomViewModel.kt
  app/src/main/res/animator/animator_storage_indicator.xml
  app/src/main/res/drawable/shape_spark_dark_pinkred_line_rect.xml
  app/src/main/res/layout/activity_certify.xml
  app/src/main/res/layout/activity_habit.xml
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/activity_join_code.xml
  app/src/main/res/layout/activity_storage_photo_collection.xml
  app/src/main/res/layout/bottom_sheet_habit_today.xml
  app/src/main/res/layout/fragment_input_code_dialog.xml
  app/src/main/res/layout/fragment_name_setting.xml
  app/src/main/res/layout/fragment_select_confirm_method.xml
  app/src/main/res/layout/fragment_set_purpose.xml
  app/src/main/res/layout/fragment_storage.xml
  app/src/main/res/layout/fragment_storage_complete.xml
  app/src/main/res/layout/fragment_storage_incomplete.xml
  app/src/main/res/layout/fragment_storage_progressing.xml
  app/src/main/res/layout/fragment_waiting_room.xml
  app/src/main/res/layout/item_habit_team.xml
  app/src/main/res/layout/item_storage_complete_list.xml
  app/src/main/res/layout/item_storage_incomplete_list.xml
  app/src/main/res/layout/item_storage_progressing_list.xml
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#187 [카메라 사용] 사진 화질 높이기
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileBottomSheet.kt
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileFragment.kt
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileViewModel.kt
  app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt
  app/src/main/java/com/spark/android/ui/certify/CertifyBottomSheet.kt
  app/src/main/java/com/spark/android/ui/certify/viewmodel/CertifyViewModel.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/java/com/spark/android/util/ImageProvider.kt
  app/src/main/res/layout/activity_certify.xml
  app/src/main/res/layout/fragment_profile.xml
Labels: 🦁연주, pull request

#190 #179 [전체화면] 포커스시 edit text 색상 바꾸기 최종 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/spark/android/ui/habit/HabitGoalManageActivity.kt
  app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt
  app/src/main/res/layout/activity_habit_goal_manage.xml
  app/src/main/res/layout/fragment_name_setting.xml
  app/src/main/res/layout/fragment_set_purpose.xml
Labels: 🐷창환, fix, refactor, pull request

#192 #191 [목표관리] 설명 텍스트 fade in,fade out 처리
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
  app/src/main/java/com/spark/android/ui/main/MainActivity.kt
  app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/java/com/spark/android/util/AnimationUtil.kt
Labels: 🐷창환, feat, pull request

#194 [보관함] 보관함 뷰페이저에 애니메이션 추가
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StorageCompleteFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StorageFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StorageIncompleteFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StorageProgressingFragment.kt
  app/src/main/java/com/spark/android/ui/storage/ZoomOutPageTransformer.kt
  app/src/main/java/com/spark/android/ui/storage/viewmodel/StorageViewModel.kt
Labels: 🦁연주, pull request

#195 #188 [fix] 사진 회전되어서 서버에 보내지는 문제 해결
  app/src/main/java/com/spark/android/util/MultiPartResolver.kt
Labels: 🦁연주, pull request

#196 #193 [목표관리] edit text 부분 올라가고 내려가는것 애니메이션으로 부드럽게 처리하기
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt
  app/src/main/java/com/spark/android/util/AnimationUtil.kt
  app/src/main/java/com/spark/android/util/KeyBoardUtil.kt
  app/src/main/java/com/spark/android/util/KeyboardVisibilityUtils.kt
  app/src/main/res/layout/fragment_set_purpose.xml
Labels: 🐷창환, feat, refactor, pull request

#203 #202 [목표관리] 백버튼으로 클릭시 포커스 사라지지 않는것 수정
  app/src/main/java/com/spark/android/ui/home/adapter/HomeRecyclerViewAdapter.kt
  app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt
Labels: 🐷창환, fix, pull request

#205 #204 [목표관리] 목표관리화면 백버튼 눌렀을때 튕기는거 잡기 + 백버튼눌렀을시 대기방으로 넘어지않던 버그 해결
  app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt
Labels: 🐷창환, fix, pull request
