Repository TeamSparker/Spark-Android, pull requests merged in 2022-03, with the labels that each got.

#279 [인증완료알림] 이미지 유효하지 않을 시 기본 사진으로 알림 띄우도록 설정 수정
  app/src/main/java/com/spark/android/SparkMessagingService.kt
Labels: 🦁연주, pull request

#281 [푸쉬알람] 카테고리 나눈 알람들 ChannelId 다르게 설정하기
  app/src/main/java/com/spark/android/SparkMessagingService.kt
Labels: 🦁연주, pull request

#284 #272,282.283 [방만들기,대기방] 방만들기 중간페이지 생성 ,인텐트관계정리,애니메이션 최신화
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt
  app/src/main/java/com/spark/android/ui/makeroom/selectconfirmmethod/SelectConfirmMethodFragment.kt
  app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomActivity.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/checkroom/CheckRoomFragment.kt
  app/src/main/java/com/spark/android/util/AnimationUtil.kt
  app/src/main/java/com/spark/android/util/DialogUtil.kt
  app/src/main/res/animator/animator_toast_message.xml
  app/src/main/res/layout/fragment_check_room.xml
  app/src/main/res/layout/fragment_waiting_room.xml
  app/src/main/res/values/strings.xml
Labels: 🐷창환, feat, layout, pull request

#286 #285 [대기방] 대기방 인원목록 리사이클러뷰 diffutil 리펙토링
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/adapter/WaitingRoomRecyclerViewAdapter.kt
Labels: 🐷창환, refactor, pull request

#288 #287 [대기방,방만들기] 코드복사 버튼 중복터치 막기 및 액티비티 종료시 애니메이션 같이 종료시켜 튕김현상 방지 작업
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/checkroom/CheckRoomFragment.kt
  app/src/main/java/com/spark/android/util/AnimationUtil.kt
Labels: 🐷창환, feat, pull request

#290 #289 [방생성] 방생성 다이얼로그 텍스트 내용 수정 + onpause에서 애니메이션 종료관련 버그 fix
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/checkroom/CheckRoomFragment.kt
  app/src/main/res/values/strings.xml
Labels: 🐷창환, layout, fix, pull request

#291 #273 [습관방] 쉴래요 사용하기 다이얼로그 추가
  app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt
  app/src/main/java/com/spark/android/util/DialogUtil.kt
  app/src/main/res/values/strings.xml
Labels: 🐉재훈, pull request

#294 #293 [습관방] 쉴래요 버튼 비활성화 조건 수정
  app/src/main/res/layout/bottom_sheet_habit_today.xml
Labels: 🐉재훈, pull request

#300 #298, #299 [전체 및 푸쉬알림] 앱 재설치 시 발생하는 에러들 해결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/SparkMessagingService.kt
  app/src/main/res/xml/data_extraction_rules.xml
Labels: 🦁연주, pull request

#302 #297 [대기방] 대기방 더보기 추가
  app/src/main/res/drawable/ic_watitng_room_extra_menu.xml
  app/src/main/res/layout/fragment_waiting_room.xml
  app/src/main/res/values/strings.xml
Labels: 🐷창환, layout, pull request

#306 #262 [layout] 보관함 카드 내부테두리 세로길이 조정
  app/src/main/res/layout/fragment_storage.xml
  app/src/main/res/layout/item_storage_complete_list.xml
  app/src/main/res/layout/item_storage_progressing_list.xml
  app/src/main/res/values/strings.xml
Labels: 🐬호재, layout, pull request

#308 #307 [습관방] 나의 목표 수정 뷰 수정완료 버튼 섀도우 삭제
  app/src/main/res/layout/activity_habit_goal_manage.xml
Labels: 🐉재훈, pull request

#309 #304 [대기방] 대기방 방나가기 다이얼로그 서버 + 홈 토스트 빼고 완료
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/bottomsheet/WaitingRoomFragmentBottomSheet.kt
  app/src/main/java/com/spark/android/util/DialogUtil.kt
  app/src/main/res/layout/fragment_waiting_room_bottom_sheet.xml
  app/src/main/res/values/strings.xml
Labels: 🐷창환, feat, pull request

#311 #310 [대기방] 방생성 확인 다이얼로그 생성
  app/src/main/java/com/spark/android/ui/joincode/inputcode/InputCodeFragmentDialog.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/makeroomcheckdialog/MakeRoomCheckFragmentDialog.kt
  app/src/main/res/drawable-hdpi/ic_make_room_check_dialog_person.png
  app/src/main/res/drawable-hdpi/ic_make_room_check_dialog_phone.png
  app/src/main/res/drawable-mdpi/ic_make_room_check_dialog_person.png
  app/src/main/res/drawable-mdpi/ic_make_room_check_dialog_phone.png
  app/src/main/res/drawable-xhdpi/ic_make_room_check_dialog_person.png
  app/src/main/res/drawable-xhdpi/ic_make_room_check_dialog_phone.png
  app/src/main/res/drawable-xxhdpi/ic_make_room_check_dialog_person.png
  app/src/main/res/drawable-xxhdpi/ic_make_room_check_dialog_phone.png
  app/src/main/res/drawable-xxxhdpi/ic_make_room_check_dialog_person.png
  app/src/main/res/drawable-xxxhdpi/ic_make_room_check_dialog_phone.png
  app/src/main/res/layout/fragment_make_room_check_dialog.xml
  app/src/main/res/values/strings.xml
Labels: 🐷창환, feat, pull request

#313 #277 [마이페이지] 마이페이지 레이아웃 제작
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/ui/alarmsetting/AlarmSettingFragment.kt
  app/src/main/java/com/spark/android/ui/mypage/MyPageActivity.kt
  app/src/main/java/com/spark/android/ui/mypage/MyPageMainFragment.kt
  app/src/main/java/com/spark/android/ui/withdrawal/WithdrawalFragment.kt
  app/src/main/res/drawable/ic_back_black.xml
  app/src/main/res/drawable/ic_check_box_checked.xml
  app/src/main/res/drawable/ic_check_box_unchecked.xml
  app/src/main/res/drawable/ic_my_page_arrow.xml
  app/src/main/res/drawable/selector_check_box.xml
  app/src/main/res/drawable/selector_switch_thumb.xml
  app/src/main/res/drawable/selector_switch_track.xml
  app/src/main/res/drawable/shape_light_gray_line_circle.xml
  app/src/main/res/drawable/shape_spark_gray_rect.xml
  app/src/main/res/drawable/shape_spark_light_gray_circle.xml
  app/src/main/res/drawable/shape_spark_light_pinkred_rect.xml
  app/src/main/res/drawable/shape_spark_pinkred_circle.xml
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/layout/fragment_alarm_setting.xml
  app/src/main/res/layout/fragment_my_page_main.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_withdrawal.xml
  app/src/main/res/layout/item_habit_team.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🦁연주, layout

#315 #312 [대기방,홈_메인] 방 나가기 방 삭제하기 기능 구현 및 홈에서 토스트 메세지 띄우기
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesHomeDataSource.kt
  app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesHomeDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesWaitingRoomDataSource.kt
  app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesWaitingRoomDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/datasource/RemoteWaitingRoomDataSource.kt
  app/src/main/java/com/spark/android/data/remote/datasource/RemoteWaitingRoomDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/HomeRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/WaitingRoomInfoRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/WaitingRoomInfoRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/DeleteRoomService.kt
  app/src/main/java/com/spark/android/data/remote/service/LeaveRoomService.kt
  app/src/main/java/com/spark/android/di/LocalDataSourceModule.kt
  app/src/main/java/com/spark/android/di/RemoteDataSourceModule.kt
  app/src/main/java/com/spark/android/di/RepositoryModule.kt
  app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
  app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt
  app/src/main/java/com/spark/android/ui/waitingroom/bottomsheet/WaitingRoomFragmentBottomSheet.kt
  app/src/main/java/com/spark/android/ui/waitingroom/viewmodel/WaitingRoomViewModel.kt
  app/src/main/res/layout/fragment_home_main.xml
  app/src/main/res/layout/fragment_waiting_room_bottom_sheet.xml
  app/src/main/res/values/strings.xml
Labels: 🐷창환, feat, pull request

#317 #316 [방입장_코드 입력] 백스택에 다이얼로그 ,fab 켜져있는거 끄기
  app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt
  app/src/main/java/com/spark/android/ui/joincode/inputcode/InputCodeFragmentDialog.kt
  app/src/main/java/com/spark/android/ui/main/MainActivity.kt
Labels: 🐷창환, fix, pull request

#319 #318 [방생성] 습관방 생성 확인 뷰 로티 추가
  app/src/main/res/layout/fragment_check_room.xml
Labels: 🐷창환, layout, pull request

#324 #322 [홈_메인] 완료,실패방 지옥보내기 api붙이기 완료
  app/src/main/java/com/spark/android/data/remote/datasource/RemoteHomeDataSource.kt
  app/src/main/java/com/spark/android/data/remote/datasource/RemoteHomeDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/HomeRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/HomeHabitRoomFinishService.kt
  app/src/main/java/com/spark/android/di/RemoteDataSourceModule.kt
  app/src/main/java/com/spark/android/di/RepositoryModule.kt
  app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
  app/src/main/java/com/spark/android/ui/home/adapter/HomeRecyclerViewAdapter.kt
  app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt
Labels: 🐷창환, feat, pull request

#329 #326 [마이페이지] 마이페이지 기능 및 서버 연결
  app/src/main/java/com/spark/android/data/remote/datasource/ProfileDataSource.kt
  app/src/main/java/com/spark/android/data/remote/datasource/ProfileDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/entity/response/ProfileResponse.kt
  app/src/main/java/com/spark/android/data/remote/repository/ProfileRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/ProfileRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/ProfileService.kt
  app/src/main/java/com/spark/android/di/RemoteDataSourceModule.kt
  app/src/main/java/com/spark/android/di/RepositoryModule.kt
  app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt
  app/src/main/java/com/spark/android/ui/mypage/MyPageMainFragment.kt
  app/src/main/java/com/spark/android/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/layout/fragment_my_page_main.xml
Labels: 🦁연주, feat

#331 #327 [프로필 수정] 프로필 수정 기능 및 서버 연결
  app/src/main/java/com/spark/android/SparkMessagingService.kt
  app/src/main/java/com/spark/android/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/datasource/ProfileDataSource.kt
  app/src/main/java/com/spark/android/data/remote/datasource/ProfileDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/ProfileRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/ProfileRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/ProfileService.kt
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileFragment.kt
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileViewModel.kt
  app/src/main/java/com/spark/android/ui/auth/signin/SignInFragment.kt
  app/src/main/java/com/spark/android/ui/mypage/MyPageActivity.kt
  app/src/main/java/com/spark/android/ui/mypage/MyPageMainFragment.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/java/com/spark/android/util/ImageProvider.kt
  app/src/main/java/com/spark/android/util/MultiPartResolver.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/navigation/auth_nav_graph.xml
  app/src/main/res/navigation/my_page_nav_graph.xml
Labels: 🦁연주, pull request

#332 #328 [알림 설정] 알림 설정 기능 및 서버 연결
  app/src/main/java/com/spark/android/data/remote/datasource/AlarmSettingDataSource.kt
  app/src/main/java/com/spark/android/data/remote/datasource/AlarmSettingDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/entity/response/AlarmSettingResponse.kt
  app/src/main/java/com/spark/android/data/remote/repository/AlarmSettingRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/AlarmSettingRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/AlarmSettingService.kt
  app/src/main/java/com/spark/android/di/RemoteDataSourceModule.kt
  app/src/main/java/com/spark/android/di/RepositoryModule.kt
  app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt
  app/src/main/java/com/spark/android/ui/alarmsetting/AlarmSettingFragment.kt
  app/src/main/java/com/spark/android/ui/alarmsetting/AlarmSettingViewModel.kt
  app/src/main/java/com/spark/android/ui/feed/FeedViewModel.kt
  app/src/main/java/com/spark/android/ui/mypage/MyPageViewModel.kt
  app/src/main/res/layout/fragment_alarm_setting.xml
Labels: 🦁연주, pull request

#333 #325 [홈_메인] 성공방,실패방 클릭시 다이얼로그 생성
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
  app/src/main/java/com/spark/android/ui/home/adapter/HomeRecyclerViewAdapter.kt
  app/src/main/java/com/spark/android/ui/home/finishroomdialog/FinishRoomDialogFragment.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/drawable-hdpi/bg_home_finish_dialog.png
  app/src/main/res/drawable-mdpi/bg_home_finish_dialog.png
  app/src/main/res/drawable-xhdpi/bg_home_finish_dialog.png
  app/src/main/res/drawable-xxhdpi/bg_home_finish_dialog.png
  app/src/main/res/drawable-xxxhdpi/bg_home_finish_dialog.png
  app/src/main/res/layout/fragment_finish_room_dialog.xml
  app/src/main/res/values/strings.xml
Labels: 🐷창환, feat, pull request

#335 #334 [회원탈퇴] 회원탈퇴 기능 구현 (서버연결 x)
  app/src/main/java/com/spark/android/ui/withdrawal/WithdrawalFragment.kt
  app/src/main/java/com/spark/android/ui/withdrawal/WithdrawalViewModel.kt
  app/src/main/java/com/spark/android/util/DialogUtil.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_withdrawal.xml
  app/src/main/res/values/strings.xml
Labels: 🦁연주, feat

#337 #336 [문의하기] 메일 앱 연결
  app/build.gradle
  app/src/main/java/com/spark/android/ui/mypage/MyPageMainFragment.kt
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#339 #261 [인증사진 모아보기] 대표이미지 변경 뷰 레이아웃
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/ui/storage/adapter/PhotoCollectionRvAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/adapter/PhotoMainPickRvAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/photo/PhotoCollectionMoreBottomSheet.kt
  app/src/main/java/com/spark/android/ui/storage/photo/StorageCardMainPhotoPickActivity.kt
  app/src/main/java/com/spark/android/ui/storage/photo/StoragePhotoCollectionActivity.kt
  app/src/main/java/com/spark/android/ui/storage/photo/StoragePhotoMainPickActivity.kt
  app/src/main/java/com/spark/android/ui/storage/viewmodel/PhotoViewModel.kt
  app/src/main/res/drawable-hdpi/img_photo_collection_yogurt.jpg
  app/src/main/res/layout/activity_storage_photo_collection.xml
  app/src/main/res/layout/activity_storage_photo_main_pick.xml
  app/src/main/res/layout/item_photo_collection_list.xml
  app/src/main/res/layout/item_photo_main_pick_list.xml
Labels: 🐬호재, feat

#343 #338 [홈_메인] 완료,실패방 다이얼로그 진행후 방목록 새로고침 하기
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
Labels: 🐷창환, feat, pull request

#346 #261 [feat] 대표이미지 창 PATCH Retrofit interface 만듦
  app/src/main/java/com/spark/android/data/remote/service/PhotoMainService.kt
  app/src/main/java/com/spark/android/ui/storage/viewmodel/PhotoViewModel.kt
Labels: 🐬호재, feat

#347 #344 [홈_메인] 습관방,대기방 티켓 에셋 변경(왜 안드에게 사과거를 주시나요 ㅠㅠ)
  app/src/main/res/drawable-hdpi/img_home_left_ticket_1.png
  app/src/main/res/drawable-hdpi/img_home_left_ticket_2.png
  app/src/main/res/drawable-hdpi/img_home_left_ticket_3.png
  app/src/main/res/drawable-hdpi/img_home_left_ticket_4.png
  app/src/main/res/drawable-hdpi/img_home_left_ticket_5.png
  app/src/main/res/drawable-hdpi/img_home_left_ticket_6.png
  app/src/main/res/drawable-hdpi/img_home_left_ticket_waiting.png
  app/src/main/res/drawable-hdpi/img_home_right_ticket.png
  app/src/main/res/drawable-hdpi/img_home_right_ticket_fold.png
  app/src/main/res/drawable-hdpi/img_home_right_ticket_waiting.png
  app/src/main/res/drawable-mdpi/img_home_left_ticket_1.png
  app/src/main/res/drawable-mdpi/img_home_left_ticket_2.png
  app/src/main/res/drawable-mdpi/img_home_left_ticket_3.png
  app/src/main/res/drawable-mdpi/img_home_left_ticket_4.png
  app/src/main/res/drawable-mdpi/img_home_left_ticket_5.png
  app/src/main/res/drawable-mdpi/img_home_left_ticket_6.png
  app/src/main/res/drawable-mdpi/img_home_left_ticket_waiting.png
  app/src/main/res/drawable-mdpi/img_home_right_ticket.png
  app/src/main/res/drawable-mdpi/img_home_right_ticket_fold.png
  app/src/main/res/drawable-mdpi/img_home_right_ticket_waiting.png
  app/src/main/res/drawable-xhdpi/img_home_left_ticket_1.png
  app/src/main/res/drawable-xhdpi/img_home_left_ticket_2.png
  app/src/main/res/drawable-xhdpi/img_home_left_ticket_3.png
  app/src/main/res/drawable-xhdpi/img_home_left_ticket_4.png
  app/src/main/res/drawable-xhdpi/img_home_left_ticket_5.png
  app/src/main/res/drawable-xhdpi/img_home_left_ticket_6.png
  app/src/main/res/drawable-xhdpi/img_home_left_ticket_waiting.png
  app/src/main/res/drawable-xhdpi/img_home_right_ticket.png
  app/src/main/res/drawable-xhdpi/img_home_right_ticket_fold.png
  app/src/main/res/drawable-xhdpi/img_home_right_ticket_waiting.png
  app/src/main/res/drawable-xxhdpi/img_home_left_ticket_1.png
  app/src/main/res/drawable-xxhdpi/img_home_left_ticket_2.png
  app/src/main/res/drawable-xxhdpi/img_home_left_ticket_3.png
  app/src/main/res/drawable-xxhdpi/img_home_left_ticket_4.png
  app/src/main/res/drawable-xxhdpi/img_home_left_ticket_5.png
  app/src/main/res/drawable-xxhdpi/img_home_left_ticket_6.png
  app/src/main/res/drawable-xxhdpi/img_home_left_ticket_waiting.png
  app/src/main/res/drawable-xxhdpi/img_home_right_ticket.png
  app/src/main/res/drawable-xxhdpi/img_home_right_ticket_fold.png
  app/src/main/res/drawable-xxhdpi/img_home_right_ticket_waiting.png
  app/src/main/res/drawable-xxxhdpi/img_home_left_ticket_1.png
  app/src/main/res/drawable-xxxhdpi/img_home_left_ticket_2.png
  app/src/main/res/drawable-xxxhdpi/img_home_left_ticket_3.png
  app/src/main/res/drawable-xxxhdpi/img_home_left_ticket_4.png
  app/src/main/res/drawable-xxxhdpi/img_home_left_ticket_5.png
  app/src/main/res/drawable-xxxhdpi/img_home_left_ticket_6.png
  app/src/main/res/drawable-xxxhdpi/img_home_left_ticket_waiting.png
  app/src/main/res/drawable-xxxhdpi/img_home_right_ticket.png
  app/src/main/res/drawable-xxxhdpi/img_home_right_ticket_fold.png
  app/src/main/res/drawable-xxxhdpi/img_home_right_ticket_waiting.png
Labels: 🐷창환, layout, pull request

#349 #348 [다이얼로그] 다이얼로그 마진값 수정
  app/src/main/java/com/spark/android/ui/home/finishroomdialog/FinishRoomDialogFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/makeroomcheckdialog/MakeRoomCheckFragmentDialog.kt
Labels: 🐷창환, fix, pull request

#352 #350 [인증 완료 다이얼로그] 날짜별 분기처리 및 레이아웃 수정
  app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt
  app/src/main/java/com/spark/android/ui/certify/CertifyBottomSheet.kt
  app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt
  app/src/main/java/com/spark/android/ui/share/InstaShareDialogFragment.kt
  app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/java/com/spark/android/util/DialogUtil.kt
  app/src/main/res/layout/dialog_insta_share.xml
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#356 #353 [전체] 수정작업
  app/src/main/java/com/spark/android/SparkMessagingService.kt
  app/src/main/java/com/spark/android/ui/share/InstaShareDialogFragment.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/drawable/ic_check_box_unchecked.xml
  app/src/main/res/layout/dialog_insta_share.xml
Labels: 🦁연주, pull request

#357 #341 [알림센터] 알림 센터 레이아웃 및 알림 리스트 레이아웃 제작
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/ui/alarmcenter/AlarmCenterActivity.kt
  app/src/main/java/com/spark/android/ui/alarmcenter/NoticeAlarmFragment.kt
  app/src/main/java/com/spark/android/ui/alarmcenter/SparkActivityAlarmFragment.kt
  app/src/main/res/drawable/ic_alarm_circle_sticker.xml
  app/src/main/res/layout/activity_alarm_center.xml
  app/src/main/res/layout/fragment_notice_alarm.xml
  app/src/main/res/layout/fragment_spark_activity_alarm.xml
  app/src/main/res/layout/item_alarm_list.xml
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#359 #358 [홈_메인] 홈 리사이클러뷰 하단 fab에 겹치지 않도록 마진주기
  app/src/main/res/layout/fragment_home_main.xml
Labels: 🐷창환, feat, pull request

#360 #351 [홈_메인] 다이얼로그 로티 이미지 넣기
  app/src/main/assets/home_card_fail.json
  app/src/main/assets/home_card_success.json
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/layout/fragment_finish_room_dialog.xml
Labels: 🐷창환, feat, pull request

#363 #340 [대표사진 선택창] 완료버튼 누르면 서버에 patch 기능 구현
  app/src/main/java/com/spark/android/data/remote/RetrofitBuilder.kt
  app/src/main/java/com/spark/android/data/remote/service/PhotoMainService.kt
  app/src/main/java/com/spark/android/ui/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/spark/android/ui/storage/adapter/PhotoMainPickRvAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/photo/StoragePhotoMainPickActivity.kt
  app/src/main/java/com/spark/android/ui/storage/viewmodel/PhotoViewModel.kt
  app/src/main/res/layout/activity_on_boarding.xml
Labels: 🐬호재, feat, pull request

#365 #342 [알림센터] 알림 센터 기능 및 서버 연결
  app/build.gradle
  app/src/main/java/com/spark/android/data/remote/datasource/AlarmCenterDataSource.kt
  app/src/main/java/com/spark/android/data/remote/datasource/AlarmCenterDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/entity/response/AlarmResponse.kt
  app/src/main/java/com/spark/android/data/remote/repository/AlarmCenterRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/AlarmCenterRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/AlarmCenterService.kt
  app/src/main/java/com/spark/android/di/RemoteDataSourceModule.kt
  app/src/main/java/com/spark/android/di/RepositoryModule.kt
  app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt
  app/src/main/java/com/spark/android/ui/alarmcenter/AlarmCenterActivity.kt
  app/src/main/java/com/spark/android/ui/alarmcenter/NoticeAlarmFragment.kt
  app/src/main/java/com/spark/android/ui/alarmcenter/SparkActivityAlarmFragment.kt
  app/src/main/java/com/spark/android/ui/alarmcenter/alarms/ActivityAlarmFragment.kt
  app/src/main/java/com/spark/android/ui/alarmcenter/alarms/AlarmType.kt
  app/src/main/java/com/spark/android/ui/alarmcenter/alarms/ServiceAlarmFragment.kt
  app/src/main/java/com/spark/android/ui/alarmcenter/alarms/adapter/AlarmPagingAdapter.kt
  app/src/main/java/com/spark/android/ui/alarmcenter/alarms/pagingsource/AlarmPagingSource.kt
  app/src/main/java/com/spark/android/ui/alarmcenter/alarms/viewmodel/ActivityAlarmViewModel.kt
  app/src/main/java/com/spark/android/ui/alarmcenter/alarms/viewmodel/ServiceAlarmViewModel.kt
  app/src/main/java/com/spark/android/ui/alarmcenter/viewmodel/AlarmCenterViewModel.kt
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/animator/animator_storage_indicator.xml
  app/src/main/res/drawable/ic_alarm_center_empty.xml
  app/src/main/res/layout/activity_alarm_center.xml
  app/src/main/res/layout/fragment_activity_alarm.xml
  app/src/main/res/layout/fragment_home_main.xml
  app/src/main/res/layout/fragment_notice_alarm.xml
  app/src/main/res/layout/fragment_service_alarm.xml
  app/src/main/res/layout/fragment_spark_activity_alarm.xml
  app/src/main/res/layout/item_alarm_list.xml
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#366 #126 [홈_메인] 홈 무한스크롤 구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/spark/android/data/remote/entity/response/HomeResponse.kt
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
  app/src/main/java/com/spark/android/ui/home/adapter/HomeRecyclerViewAdapter.kt
  app/src/main/java/com/spark/android/ui/home/adapter/multiview/HomeRecyclerViewMulitMode.kt
  app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt
  app/src/main/res/layout/item_home_loading.xml
Labels: 🐷창환, feat, pull request

#371 [마이페이지, 로그인] 약관 및 정책, 오픈소스 라이선스 링크 연결
  app/src/main/java/com/spark/android/ui/alarmcenter/alarms/ActivityAlarmFragment.kt
  app/src/main/java/com/spark/android/ui/alarmcenter/alarms/ServiceAlarmFragment.kt
  app/src/main/java/com/spark/android/ui/auth/signin/SignInFragment.kt
  app/src/main/java/com/spark/android/ui/mypage/MyPageMainFragment.kt
  app/src/main/res/layout/fragment_alarm_setting.xml
  app/src/main/res/layout/fragment_my_page_main.xml
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/layout/fragment_withdrawal.xml
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#372 #362 [습관방] 습관방 나가기 후 홈 화면으로 이동 적용
  app/src/main/java/com/spark/android/data/remote/LocalPreferences.kt
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitMoreBottomSheet.kt
  app/src/main/java/com/spark/android/util/DialogEditTextUtil.kt
  app/src/main/res/layout/dialog_edit_text_util.xml
Labels: 🐉재훈, pull request

#373 #364 [습관방] 습관방 이용가이드 레이아웃 작업 완료(인디케이터 작업 빼고)
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/spark/android/ui/habit/userguide/UserGuideFirstFragment.kt
  app/src/main/java/com/spark/android/ui/habit/userguide/UserGuideFragmentDialog.kt
  app/src/main/java/com/spark/android/ui/habit/userguide/UserGuideSecondFragment.kt
  app/src/main/java/com/spark/android/ui/habit/userguide/UserGuideThirdFragment.kt
  app/src/main/java/com/spark/android/ui/habit/userguide/adapter/UserGuideAdapter.kt
  app/src/main/java/com/spark/android/ui/home/finishroomdialog/FinishRoomDialogFragment.kt
  app/src/main/java/com/spark/android/ui/joincode/inputcode/InputCodeFragmentDialog.kt
  app/src/main/java/com/spark/android/ui/waitingroom/makeroomcheckdialog/MakeRoomCheckFragmentDialog.kt
  app/src/main/res/layout/fragment_user_guide_dialog.xml
  app/src/main/res/layout/fragment_user_guide_first.xml
  app/src/main/res/layout/fragment_user_guide_second.xml
  app/src/main/res/layout/fragment_user_guide_third.xml
  app/src/main/res/values/strings.xml
Labels: 🐷창환, feat, pull request

#375 #374 [습관방] 눈물의 닷 인디케이터 만들기 완료
  app/src/main/java/com/spark/android/ui/habit/userguide/UserGuideFragmentDialog.kt
  app/src/main/res/drawable/dot_indicator_dot_selected.xml
  app/src/main/res/drawable/dot_indicator_dot_unselected.xml
  app/src/main/res/layout/fragment_user_guide_dialog.xml
Labels: 🐷창환, feat, pull request

#377 #369 [마이페이지] 회원탈퇴 기능, 로그아웃 및 서버 연결
  app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesDataSource.kt
  app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/datasource/AuthDataSource.kt
  app/src/main/java/com/spark/android/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/AuthRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/AuthService.kt
  app/src/main/java/com/spark/android/ui/auth/signin/SignInViewModel.kt
  app/src/main/java/com/spark/android/ui/mypage/MyPageMainFragment.kt
  app/src/main/java/com/spark/android/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/spark/android/ui/withdrawal/WithdrawalFragment.kt
  app/src/main/java/com/spark/android/ui/withdrawal/WithdrawalViewModel.kt
  app/src/main/res/layout/fragment_my_page_main.xml
  app/src/main/res/layout/fragment_withdrawal.xml
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#378 Feature/on boarding connecting
  app/src/main/java/com/spark/android/ui/intro/IntroActivity.kt
  app/src/main/java/com/spark/android/ui/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/spark/android/ui/storage/viewmodel/PhotoViewModel.kt
  app/src/main/res/layout/fragment_on_boarding_four.xml
  app/src/main/res/values/strings.xml
Labels: 🐬호재, feat, pull request

#379 #370 [스플래시] 도어벨 api 연결
  app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesDataSource.kt
  app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/spark/android/ui/intro/IntroActivity.kt
  app/src/main/java/com/spark/android/ui/intro/IntroViewModel.kt
Labels: 🦁연주, pull request

#382 #380 [피드] 신고하기 레이아웃
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/ui/feedreport/FeedReportActivity.kt
  app/src/main/res/drawable/ic_feed_more.xml
  app/src/main/res/drawable/shape_spark_gray_line_rect_2.xml
  app/src/main/res/layout/activity_feed_report.xml
  app/src/main/res/layout/bottom_sheet_feed.xml
  app/src/main/res/layout/fragment_my_page_main.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_withdrawal.xml
  app/src/main/res/layout/item_feed_content.xml
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#383 #381 [피드] 신고하기 기능 및 서버 연결
  app/src/main/java/com/spark/android/data/remote/datasource/FeedDataSource.kt
  app/src/main/java/com/spark/android/data/remote/datasource/FeedDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/entity/request/FeedReportRequest.kt
  app/src/main/java/com/spark/android/data/remote/entity/response/FeedResponse.kt
  app/src/main/java/com/spark/android/data/remote/repository/FeedRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/FeedRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/FeedService.kt
  app/src/main/java/com/spark/android/ui/feed/FeedBottomSheet.kt
  app/src/main/java/com/spark/android/ui/feed/FeedFragment.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedAdapter.kt
  app/src/main/java/com/spark/android/ui/feedreport/FeedReportActivity.kt
  app/src/main/java/com/spark/android/ui/feedreport/FeedReportViewModel.kt
  app/src/main/java/com/spark/android/util/EditTextUtil.kt
  app/src/main/res/layout/activity_feed_report.xml
  app/src/main/res/layout/item_feed_content.xml
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#384 #376 [습관방] 유저 가이드 다이얼로그 local preference 에 state 저장 및 띄우는 시기 분기처리
  app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesHabitDataSource.kt
  app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesHabitDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesProfileDataSource.kt
  app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesProfileDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/HabitRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/HabitRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/ProfileRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/ProfileRepositoryImpl.kt
  app/src/main/java/com/spark/android/di/LocalDataSourceModule.kt
  app/src/main/java/com/spark/android/di/RepositoryModule.kt
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileViewModel.kt
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/java/com/spark/android/ui/habit/viewmodel/HabitViewModel.kt
Labels: 🐷창환, feat, pull request

#386 #385 [푸쉬알림] 인증완료 이미지 리사이징해서 받아오던 것 업로드하던 사이즈 그대로 받아오도록 수정
  app/src/main/java/com/spark/android/SparkMessagingService.kt
Labels: 🦁연주, pull request
