Repository TeamSparker/Spark-Android, pull requests merged in 2022-02, with the labels that each got.

#206 #204 [목표관리] onAttach 두개 있던 오류 잡기
  app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt
Labels: 🐷창환, fix, pull request

#207 #199 [타이머] 타이머 코드 리팩토링
  app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt
  app/src/main/java/com/spark/android/ui/timer/viewmodel/TimerStartViewModel.kt
Labels: 🐬호재, pull request

#209 #208 [타이머] 타이머 코드 MVVM 리팩토링
  app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt
Labels: 🐬호재, pull request

#210 #200 [홈_메인] diffutil로 리팩토링
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
  app/src/main/java/com/spark/android/ui/home/adapter/HomeRecyclerViewAdapter.kt
Labels: 🐷창환, refactor, pull request

#212 #211 [홈_메인] 로딩뷰 위치조정
  app/src/main/res/layout/fragment_home_main.xml
Labels: 🐷창환, layout, pull request

#216 #215 [홈_메인] 홈_메인 티켓 에셋이미지 변경
  app/src/main/res/drawable-hdpi/img_home_left_ticket_1.png
  app/src/main/res/drawable-hdpi/img_home_left_ticket_2.png
  app/src/main/res/drawable-hdpi/img_home_left_ticket_3.png
  app/src/main/res/drawable-hdpi/img_home_left_ticket_4.png
  app/src/main/res/drawable-hdpi/img_home_left_ticket_5.png
  app/src/main/res/drawable-hdpi/img_home_left_ticket_6.png
  app/src/main/res/drawable-hdpi/img_home_left_ticket_waiting.png
  app/src/main/res/drawable-hdpi/img_home_right_ticket.png
  app/src/main/res/drawable-hdpi/img_home_right_ticket_fold.png
  app/src/main/res/drawable-hdpi/img_home_right_ticket_waiting.png
  app/src/main/res/drawable-mdpi/img_home_left_ticket_1.png
  app/src/main/res/drawable-mdpi/img_home_left_ticket_2.png
  app/src/main/res/drawable-mdpi/img_home_left_ticket_3.png
  app/src/main/res/drawable-mdpi/img_home_left_ticket_4.png
  app/src/main/res/drawable-mdpi/img_home_left_ticket_5.png
  app/src/main/res/drawable-mdpi/img_home_left_ticket_6.png
  app/src/main/res/drawable-mdpi/img_home_left_ticket_waiting.png
  app/src/main/res/drawable-mdpi/img_home_right_ticket.png
  app/src/main/res/drawable-mdpi/img_home_right_ticket_fold.png
  app/src/main/res/drawable-mdpi/img_home_right_ticket_waiting.png
  app/src/main/res/drawable-xhdpi/img_home_left_ticket_1.png
  app/src/main/res/drawable-xhdpi/img_home_left_ticket_2.png
  app/src/main/res/drawable-xhdpi/img_home_left_ticket_3.png
  app/src/main/res/drawable-xhdpi/img_home_left_ticket_4.png
  app/src/main/res/drawable-xhdpi/img_home_left_ticket_5.png
  app/src/main/res/drawable-xhdpi/img_home_left_ticket_6.png
  app/src/main/res/drawable-xhdpi/img_home_left_ticket_waiting.png
  app/src/main/res/drawable-xhdpi/img_home_right_ticket.png
  app/src/main/res/drawable-xhdpi/img_home_right_ticket_fold.png
  app/src/main/res/drawable-xhdpi/img_home_right_ticket_waiting.png
  app/src/main/res/drawable-xxhdpi/img_home_left_ticket_1.png
  app/src/main/res/drawable-xxhdpi/img_home_left_ticket_2.png
  app/src/main/res/drawable-xxhdpi/img_home_left_ticket_3.png
  app/src/main/res/drawable-xxhdpi/img_home_left_ticket_4.png
  app/src/main/res/drawable-xxhdpi/img_home_left_ticket_5.png
  app/src/main/res/drawable-xxhdpi/img_home_left_ticket_6.png
  app/src/main/res/drawable-xxhdpi/img_home_left_ticket_waiting.png
  app/src/main/res/drawable-xxhdpi/img_home_right_ticket.png
  app/src/main/res/drawable-xxhdpi/img_home_right_ticket_fold.png
  app/src/main/res/drawable-xxhdpi/img_home_right_ticket_waiting.png
  app/src/main/res/drawable-xxxhdpi/img_home_left_ticket_1.png
  app/src/main/res/drawable-xxxhdpi/img_home_left_ticket_2.png
  app/src/main/res/drawable-xxxhdpi/img_home_left_ticket_3.png
  app/src/main/res/drawable-xxxhdpi/img_home_left_ticket_4.png
  app/src/main/res/drawable-xxxhdpi/img_home_left_ticket_5.png
  app/src/main/res/drawable-xxxhdpi/img_home_left_ticket_6.png
  app/src/main/res/drawable-xxxhdpi/img_home_left_ticket_waiting.png
  app/src/main/res/drawable-xxxhdpi/img_home_right_ticket.png
  app/src/main/res/drawable-xxxhdpi/img_home_right_ticket_fold.png
  app/src/main/res/drawable-xxxhdpi/img_home_right_ticket_waiting.png
  app/src/main/res/layout/item_home_recyclerview.xml
Labels: 🐷창환, layout, pull request

#219 #218 [fix] 받은 스파크 아이콘 잘림 현상 해결
  app/src/main/res/drawable-hdpi/ic_feed_fire_gray.png
  app/src/main/res/drawable-mdpi/ic_feed_fire_gray.png
  app/src/main/res/drawable-xhdpi/ic_feed_fire_gray.png
  app/src/main/res/drawable-xxhdpi/ic_feed_fire_gray.png
  app/src/main/res/drawable-xxxhdpi/ic_feed_fire_gray.png
  app/src/main/res/drawable/ic_feed_fire_gray.xml
Labels: 🦁연주, pull request

#221 [습관방] 목표 관리 애니메이션 추가
  app/src/main/java/com/spark/android/ui/habit/HabitGoalManageActivity.kt
  app/src/main/res/layout/activity_habit_goal_manage.xml
Labels: 🐉재훈, pull request

#223 [습관방] 스파크 보내기 버튼 여러 차례 클릭 불가능하도록 수정
  app/src/main/java/com/spark/android/ui/habit/HabitSendSparkBottomSheet.kt
Labels: 🐉재훈, pull request

#224 [타이머] 타이머 코드 MVVM 리팩토링
  app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt
  app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt
  app/src/main/res/layout/activity_timer_start.xml
  app/src/main/res/layout/fragment_storage_complete.xml
  app/src/main/res/layout/fragment_storage_incomplete.xml
  app/src/main/res/layout/fragment_storage_progressing.xml
  app/src/main/res/layout/item_photo_collection_list.xml
  app/src/main/res/layout/item_storage_complete_list.xml
  app/src/main/res/layout/item_storage_incomplete_list.xml
  app/src/main/res/layout/item_storage_progressing_list.xml
  app/src/main/res/values/strings.xml
Labels: 🐬호재, refactor

#226 #220 [방 생성] 코드로 입장 edit text 밑줄색상 조건 일치시키기
  app/src/main/java/com/spark/android/ui/joincode/inputcode/InputCodeFragmentDialog.kt
  app/src/main/res/layout/fragment_input_code_dialog.xml
Labels: 🐷창환, fix, pull request

#228 #217 [홈_메인] fab 그림자 색상변경(추후에 제플린에서 받은 이미지 바꿔야함)
  app/src/main/res/drawable/shadow_spark_dark_pinkred.png
  app/src/main/res/layout/activity_main.xml
Labels: 🐷창환, feat, layout

#229 #227 [홈_메인] 홈플로팅 버튼 눌렀다가 닫았을때 종종 흰색으로 바뀌는 오류수정
  app/src/main/java/com/spark/android/ui/main/MainActivity.kt
Labels: 🐷창환, fix, pull request

#231 #230 [홈_메인] fab열려있을시 백버튼 처리(fab 닫도록 처리)
  app/src/main/java/com/spark/android/ui/main/MainActivity.kt
Labels: 🐷창환, feat, pull request

#232 #217 [홈_메인] fab 그림자 색상 변경 완료
  app/src/main/res/drawable-hdpi/shadow_spark_dark_pinkred.png
  app/src/main/res/drawable-mdpi/shadow_spark_dark_pinkred.png
  app/src/main/res/drawable-xhdpi/shadow_spark_dark_pinkred.png
  app/src/main/res/drawable-xxhdpi/shadow_spark_dark_pinkred.png
  app/src/main/res/drawable-xxxhdpi/shadow_spark_dark_pinkred.png
  app/src/main/res/drawable/shadow_spark_dark_pinkred.png
Labels: 🐷창환, feat, layout

#235 #222 [습관방] 리사이클러뷰 ListAdapter 리팩토링
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/java/com/spark/android/ui/habit/adapter/HabitRecyclerViewAdapter.kt
Labels: 🐉재훈, pull request

#239 #238 [습관방] 습관방 리사이클러뷰 초기화 오류 수정
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
Labels: 🐉재훈, pull request

#241 #240 [ 보관함] 총 스파크 수 필드명 수정
  app/src/main/java/com/spark/android/data/remote/entity/response/StorageResponse.kt
  app/src/main/res/layout/item_storage_complete_list.xml
  app/src/main/res/layout/item_storage_incomplete_list.xml
  app/src/main/res/layout/item_storage_progressing_list.xml
Labels: 🦁연주, pull request

#244 #242 [홈_메인] 홈에 rest 딱지 붙은거 처리 및 관련 서버 바뀐부분처리
  app/src/main/java/com/spark/android/data/remote/entity/response/HomeResponse.kt
  app/src/main/java/com/spark/android/ui/home/adapter/HomeRecyclerViewAdapter.kt
  app/src/main/java/com/spark/android/ui/home/data/TicketData.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/drawable-hdpi/ic_home_ticket_tag_rest.png
  app/src/main/res/drawable-mdpi/ic_home_ticket_tag_rest.png
  app/src/main/res/drawable-xhdpi/ic_home_ticket_tag_rest.png
  app/src/main/res/drawable-xxhdpi/ic_home_ticket_tag_rest.png
  app/src/main/res/drawable-xxxhdpi/ic_home_ticket_tag_rest.png
  app/src/main/res/layout/item_home_recyclerview.xml
Labels: 🐷창환, feat, layout, pull request

#246 #225 [습관방] 오늘의 인증 쉴래요, 고민중 선택 시 데이터 새로고침 구현
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitSendSparkBottomSheet.kt
  app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt
Labels: 🐉재훈, pull request

#248 [엠티뷰] 홈, 피드, 보관함 엠티뷰 위치 통일
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_home_main.xml
  app/src/main/res/layout/fragment_storage_complete.xml
  app/src/main/res/layout/fragment_storage_incomplete.xml
  app/src/main/res/layout/fragment_storage_progressing.xml
Labels: 🦁연주, pull request

#251 Feature/storage card center alignment
  app/src/main/res/layout/fragment_storage.xml
  app/src/main/res/layout/item_storage_complete_list.xml
  app/src/main/res/layout/item_storage_incomplete_list.xml
  app/src/main/res/layout/item_storage_progressing_list.xml
Labels: 🐬호재, pull request

#253 #252 [refactoring] 인증사진 모아보기에 rest, none 에셋 추가
  app/src/main/res/drawable-hdpi/ic_sticker_none.png
  app/src/main/res/drawable-hdpi/sticker_rest.png
  app/src/main/res/drawable-mdpi/ic_sticker_none.png
  app/src/main/res/drawable-mdpi/sticker_rest.png
  app/src/main/res/drawable-xhdpi/ic_sticker_none.png
  app/src/main/res/drawable-xhdpi/sticker_rest.png
  app/src/main/res/drawable-xxhdpi/ic_sticker_none.png
  app/src/main/res/drawable-xxhdpi/sticker_rest.png
  app/src/main/res/drawable-xxxhdpi/ic_sticker_none.png
  app/src/main/res/drawable-xxxhdpi/sticker_rest.png
Labels: 🐬호재, pull request

#255 #254 [습관방] 습관방 참여자 프로필 수정
  app/src/main/res/drawable/ic_habit_sticker_rest.xml
  app/src/main/res/drawable/shape_habit_light_gray_line_circle.xml
  app/src/main/res/layout/item_habit_team.xml
Labels: 🐉재훈, pull request

#258 #249,#250 [방생성] 서버로 요청하는 버튼들 중복클릭 막기
  .github/pull_request_template.md
  app/src/main/java/com/spark/android/ui/makeroom/selectconfirmmethod/SelectConfirmMethodFragment.kt
  app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
Labels: 🐷창환, feat, pull request

#260 #256 [refactoring] 타이머 인증시 인증사진 모아보기에 타이머 시간 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/data/remote/entity/response/PhotoCollectionResponse.kt
  app/src/main/res/layout/item_photo_collection_list.xml
Labels: 🐬호재, pull request

#264 #263 [feat] 이미지 리사이징 관련 작업
  app/src/main/java/com/spark/android/util/MultiPartResolver.kt
Labels: 🦁연주, pull request

#266 #265 [방 만들기] 습관방 생성 인증방식 선택 다이얼로그 추가
  app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt
  app/src/main/java/com/spark/android/ui/makeroom/selectconfirmmethod/SelectConfirmMethodFragment.kt
  app/src/main/java/com/spark/android/util/DialogUtil.kt
  app/src/main/res/values/strings.xml
Labels: 🐷창환, feat, pull request

#269 #257 [푸시알림] 알림 종류 별 푸시알림 레이아웃 설정
  app/src/main/java/com/spark/android/SparkMessagingService.kt
  app/src/main/java/com/spark/android/util/ImageUrlTransformer.kt
Labels: 🦁연주, pull request

#276 #275,267 [전체영역,대기방] lifecycleowner 수정,애니메이션 관련 버그 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
  app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
Labels: 🐷창환, fix, pull request
