Repository TeamSparker/Spark-Android, pull requests merged in 2022-05, with the labels that each got.

#488 #487 [트래킹] GA 트래킹 재훈
  app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitSendSparkActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt
  app/src/main/java/com/spark/android/ui/habit/adapter/HabitSendSparkRecyclerViewAdapter.kt
  app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt
Labels: 🐉재훈, pull request

#490 #489 [fix] 고민중 / 쉴래요 클릭 비정상 종료 오류 해결
  app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt
  app/src/main/java/com/spark/android/ui/habit/viewmodel/HabitViewModel.kt
Labels: 🐉재훈, pull request

#493 #492 [feat] GA 트래킹 심기
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
  app/src/main/java/com/spark/android/ui/joincode/inputcode/InputCodeFragmentDialog.kt
  app/src/main/java/com/spark/android/ui/makeroom/selectconfirmmethod/SelectConfirmMethodFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
Labels: 🐷창환, feat, pull request

#496 #495 [카메라] 카메라 사용 시 에러 해결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileBottomSheet.kt
  app/src/main/java/com/spark/android/ui/certify/CertifyBottomSheet.kt
  app/src/main/java/com/spark/android/ui/feed/FeedViewModel.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedAdapter.kt
  app/src/main/java/com/spark/android/util/ImageProvider.kt
Labels: 🦁연주, pull request

#497 #479 [스플래시] 강제 업데이트 안내 다이얼로그 추가
  app/src/main/java/com/spark/android/data/remote/datasource/AuthDataSource.kt
  app/src/main/java/com/spark/android/data/remote/datasource/AuthDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/entity/response/VersionResponse.kt
  app/src/main/java/com/spark/android/data/remote/repository/AuthRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/AuthService.kt
  app/src/main/java/com/spark/android/ui/intro/IntroActivity.kt
  app/src/main/java/com/spark/android/ui/intro/IntroViewModel.kt
  app/src/main/java/com/spark/android/ui/intro/VersionUpdateState.kt
  app/src/main/java/com/spark/android/util/DialogUtil.kt
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#499 #498 [fix] 카메라 사용 중 뒤로가기로 돌아올 때 원래 화면에 머무르도록 하기
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileBottomSheet.kt
  app/src/main/java/com/spark/android/ui/certify/CertifyBottomSheet.kt
  app/src/main/java/com/spark/android/util/ImageProvider.kt
Labels: 🦁연주, pull request

#501 #500 [modify] 이용약관, 개인정보처리방침, 약관 및 정책, 오픈소스 링크 수정
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#503 #502 [fix] 피드 신고하기 화면에서 시스템 뒤로가기 버튼 클릭 시 피드에 머무를 수 있도록 수정
  app/src/main/java/com/spark/android/ui/feedreport/FeedReportActivity.kt
Labels: 🦁연주, pull request

#505 #504 [feat] 피드 신고 완료 시 토스트 애니메이션 띄우기
  app/src/main/java/com/spark/android/ui/feed/FeedFragment.kt
  app/src/main/java/com/spark/android/ui/feedreport/FeedReportActivity.kt
  app/src/main/java/com/spark/android/ui/main/MainActivity.kt
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/navigation/main_nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#512 #491 [fix] 터치 영역 버튼 한 번 더 눌러야 눌러지는 현상 개선
  app/src/main/java/com/spark/android/ui/habit/adapter/HabitSendSparkRecyclerViewAdapter.kt
Labels: 🐉재훈, pull request

#513 #510 [난독화] release 모드일 때 난독화 설정
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/java/com/spark/android/ui/habit/HabitSendSparkBottomSheet.kt
  build.gradle
Labels: 🦁연주, pull request

#514 Revert "#510 [난독화] release 모드일 때 난독화 설정"
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/java/com/spark/android/ui/habit/HabitSendSparkBottomSheet.kt
  build.gradle
Labels: 🦁연주, pull request

#515 #510 [난독화] release 모드일 때 난독화 설정
  app/build.gradle
  app/proguard-rules.pro
  app/release/output-metadata.json
Labels: 🦁연주, pull request

#517 #516 [대기방] 새로고침 버튼 비활성화 오류 막기
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/java/com/spark/android/util/AnimationUtil.kt
Labels: 🐷창환, fix, pull request

#518 #511 [습관방] 스파크 보내기 QA
  app/src/main/java/com/spark/android/ui/habit/HabitSendSparkActivity.kt
Labels: 🐉재훈, pull request

#520 #519 [습관방] 스파크 보내기 화면에서 뒤로가기 눌러도 안꺼지는 오류 해결
  app/src/main/java/com/spark/android/ui/habit/HabitSendSparkActivity.kt
Labels: 🐉재훈, pull request

#522 #521 [습관방] 스파크 보내기 뒤로가기 종료 오류 해결
  app/src/main/java/com/spark/android/ui/habit/HabitSendSparkActivity.kt
Labels: 🐉재훈, pull request

#524 #523 [Timber] Timber 초기화
  app/release/output-metadata.json
  app/src/main/java/com/spark/android/SparkApplication.kt
Labels: 🦁연주, pull request

#526 #525 [fix] 버전 확인 후 강제 업데이트 해당 여부에 따라 이후 동작 시작 여부 설정
  app/src/main/java/com/spark/android/ui/intro/IntroActivity.kt
Labels: 🦁연주, pull request

#528 #527 [프로필 및 카메라] 프로필 입력/수정 화면에서의 시스템 뒤로가기 이벤트처리 및 카메라 권한 체크 변수에서 함수로 변경
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileBottomSheet.kt
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileFragment.kt
  app/src/main/java/com/spark/android/ui/certify/CertifyBottomSheet.kt
Labels: 🦁연주, pull request

#535 Hotfix 1.0.1
  app/src/main/java/com/teamsparker/android/ui/auth/profile/ProfileBottomSheet.kt
  app/src/main/java/com/teamsparker/android/ui/auth/profile/ProfileFragment.kt
  app/src/main/java/com/teamsparker/android/ui/certify/CertifyActivity.kt
  app/src/main/java/com/teamsparker/android/ui/certify/CertifyBottomSheet.kt
  app/src/main/java/com/teamsparker/android/ui/certify/viewmodel/CertifyViewModel.kt
  app/src/main/java/com/teamsparker/android/ui/feedreport/FeedReportActivity.kt
  app/src/main/java/com/teamsparker/android/ui/intro/IntroActivity.kt
  app/src/main/java/com/teamsparker/android/ui/intro/IntroViewModel.kt
  app/src/main/java/com/teamsparker/android/ui/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/teamsparker/android/ui/share/InstaActivity.kt
  app/src/main/java/com/teamsparker/android/util/BindingAdapters.kt
  app/src/main/res/layout/activity_feed_report.xml
  app/src/main/res/layout/activity_join_code.xml
  app/src/main/res/layout/fragment_check_room.xml
  app/src/main/res/layout/fragment_select_confirm_method.xml
  app/src/main/res/layout/fragment_waiting_room.xml
Labels: 🦁연주, pull request

#537 #536 [chore] 버전코드, 버전네임 수정
  app/build.gradle
Labels: 🦁연주, pull request

#538 #536 [chore] 버전코드, 버전네임 수정
  app/build.gradle
Labels: 🦁연주, pull request
