Repository TeamSparker/Spark-Android, pull requests merged in 2022-04, with the labels that each got.

#390 #389 [대기방] 대기방 나의 목표멘트 수정 완료
  app/src/main/res/values/strings.xml
Labels: 🐷창환, layout, pull request

#394 #387 생명감소 알림 다이얼로그 완료
  app/src/main/java/com/spark/android/data/remote/entity/response/HabitResponse.kt
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitLifeLessDialogFragment.kt
  app/src/main/res/drawable-hdpi/bg_habit_dialog_life_less_sparkflake_pattern.png
  app/src/main/res/drawable-hdpi/img_habit_dialog_life_less.png
  app/src/main/res/drawable-mdpi/bg_habit_dialog_life_less_sparkflake_pattern.png
  app/src/main/res/drawable-mdpi/img_habit_dialog_life_less.png
  app/src/main/res/drawable-xhdpi/bg_habit_dialog_life_less_sparkflake_pattern.png
  app/src/main/res/drawable-xhdpi/img_habit_dialog_life_less.png
  app/src/main/res/drawable-xxhdpi/bg_habit_dialog_life_less_sparkflake_pattern.png
  app/src/main/res/drawable-xxhdpi/img_habit_dialog_life_less.png
  app/src/main/res/drawable-xxxhdpi/bg_habit_dialog_life_less_sparkflake_pattern.png
  app/src/main/res/drawable-xxxhdpi/img_habit_dialog_life_less.png
  app/src/main/res/layout/dialog_habit_life_less.xml
  app/src/main/res/values/strings.xml
Labels: 🐬호재, feat, layout

#402 #392,393 [습관방] 더보기 바텀시트에 유저가이드 추가,유저가이드 진입지점 분기처리 (버튼visibility + 백버튼 처리)
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitMoreBottomSheet.kt
  app/src/main/java/com/spark/android/ui/habit/userguide/UserGuideFragmentDialog.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/layout/bottom_sheet_habit_more.xml
  app/src/main/res/layout/fragment_user_guide_dialog.xml
  app/src/main/res/values/strings.xml
Labels: 🐷창환, feat, pull request

#404 #403 [방_생성] 이모지 사용시 글자수 2개로 반영되는것 1로 반영되도록 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/res/layout/fragment_name_setting.xml
Labels: 🐷창환, feat, pull request

#406 #405 [방_생성] 인증방식 선택 뷰 문구 수정
  app/src/main/res/values/strings.xml
Labels: 🐷창환, layout, pull request

#407 #303 [습관방] 스파크 보내기 업데이트
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/ui/habit/HabitSendSparkActivity.kt
  app/src/main/java/com/spark/android/ui/habit/adapter/HabitRecyclerViewAdapter.kt
  app/src/main/java/com/spark/android/ui/habit/adapter/HabitSendSparkRecyclerViewAdapter.kt
  app/src/main/java/com/spark/android/ui/habit/viewmodel/HabitSendSparkViewModel.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/drawable/ic_quit_white.xml
  app/src/main/res/drawable/shape_spark_pinkred_circle_2.xml
  app/src/main/res/drawable/shape_spark_white_stroke_circle.xml
  app/src/main/res/layout/activity_habit_send_spark.xml
  app/src/main/res/layout/item_habit_send_spark_message.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🐉재훈, pull request

#410 [알림 설정] 워딩 수정 및 스위치 플로우 수정
  app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesDataSource.kt
  app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/repository/AlarmSettingRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/AlarmSettingRepositoryImpl.kt
  app/src/main/java/com/spark/android/di/RepositoryModule.kt
  app/src/main/java/com/spark/android/ui/alarmsetting/AlarmOnOff.kt
  app/src/main/java/com/spark/android/ui/alarmsetting/AlarmSettingViewModel.kt
  app/src/main/java/com/spark/android/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/spark/android/ui/withdrawal/WithdrawalViewModel.kt
  app/src/main/res/layout/fragment_alarm_setting.xml
  app/src/main/res/values/strings.xml
Labels: 🦁연주, pull request

#414 #412 [습관방] 스파크 보내기 QA 오류 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/spark/android/ui/habit/HabitSendSparkActivity.kt
  app/src/main/res/layout/activity_habit_send_spark.xml
  app/src/main/res/layout/bottom_sheet_habit_more.xml
  app/src/main/res/values/strings.xml
Labels: 🐉재훈, pull request

#415 #301 [습관방] 쉴래요 누르면 홈 화면으로 나가지는 오류 수정
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitMoreBottomSheet.kt
  app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt
  app/src/main/java/com/spark/android/ui/habit/viewmodel/HabitViewModel.kt
Labels: 🐉재훈, pull request

#417 #411 [프로필, 로그인] 레이아웃 수정, 링크 연결, 기능 확인
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileFragment.kt
  app/src/main/java/com/spark/android/ui/auth/signin/SignInFragment.kt
  app/src/main/res/layout/fragment_profile.xml
Labels: 🦁연주, pull request

#418 #214 [회원가입_프로필입력] 회원가입 프로필 화면 입력 중 돌아가기 버튼 활성화
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/java/com/spark/android/ui/auth/signin/SignInFragment.kt
  app/src/main/java/com/spark/android/ui/auth/signin/SignInViewModel.kt
  app/src/main/java/com/spark/android/ui/intro/IntroActivity.kt
  app/src/main/java/com/spark/android/ui/intro/IntroViewModel.kt
Labels: 🦁연주, pull request

#420 #416 [습관방] 스파크 보내기 QA 수정
  app/src/main/java/com/spark/android/ui/habit/HabitSendSparkActivity.kt
  app/src/main/java/com/spark/android/util/SendSparkToast.kt
  app/src/main/res/layout/activity_habit_send_spark.xml
Labels: 🐉재훈, pull request

#422 #421 [습관방] 습관방 QA 내용 수정
  app/src/main/java/com/spark/android/ui/habit/userguide/UserGuideFragmentDialog.kt
  app/src/main/res/drawable/dot_indicator_dot_unselected.xml
  app/src/main/res/layout/fragment_user_guide_dialog.xml
  app/src/main/res/values/strings.xml
Labels: 🐉재훈, pull request

#425 #424 [홈_메인] 홈 토스트 메시지 가려지는 현상 수정
  app/src/main/res/layout/fragment_home_main.xml
Labels: 🐷창환, fix, pull request

#426 #409 [방_생성] 방생성 확인 버튼 쉐도우 제거,폰트 사이즈 수정
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_check_room.xml
Labels: 🐷창환, fix, pull request

#427 #419 [방_생성] 방생성 인증 방식 확인 다이얼로그 완료버튼 문구 수정
  app/src/main/res/values/strings.xml
Labels: 🐷창환, fix, pull request

#429 #428 [대기방] 인원목록 업데이트시 함께하는 스파커 수 수정 안되는 부분 수정, 스파커 닉네임 길이조정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/spark/android/data/remote/entity/response/WaitingRoomInfoResponse.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/viewmodel/WaitingRoomViewModel.kt
  app/src/main/res/layout/fragment_waiting_room.xml
  app/src/main/res/layout/item_waiting_room_recyclerview.xml
Labels: 🐷창환, fix, pull request

#431 #430 [대기방] 습관방 만들기 버튼 텍스트 수정,다이얼로그 텍스트 띄워쓰기 수정
  app/src/main/res/values/strings.xml
Labels: 🐷창환, fix, pull request

#434 #433 [습관방 입장] 코드로 참여 오류메세지 서버에서 주는대로 내보내기
  .github/pull_request_template.md
  app/src/main/java/com/spark/android/ui/joincode/inputcode/viewModel/InputCodeFragmnetDialogViewModel.kt
Labels: 🐷창환, fix, pull request

#436 #435 [fix] 모든버튼 쉐도우 없애기
  .idea/deploymentTargetDropDown.xml
  app/src/main/res/layout/fragment_finish_room_dialog.xml
  app/src/main/res/layout/fragment_set_purpose.xml
Labels: 🐷창환, fix, pull request

#438 #432 [홈_메인] 대기방 삭제 홈 토스트 메시지 너무 길면 생략
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/bottomsheet/WaitingRoomFragmentBottomSheet.kt
Labels: 🐷창환, fix, pull request

#440 #439 [목표_작성] 기존 작성된 목표 다시 목표작성 프래그먼트에 진입 했을때 edittext에 넣어주기
  app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt
  app/src/main/java/com/spark/android/ui/setpurpose/viewmodel/SetPurposeViewModel.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
Labels: 🐷창환, fix, pull request

#441 #423 [대기방] 대기방 생성후 홈으로 이동하는 부분 습관방으로 이동하도록 수정
  app/src/main/java/com/spark/android/ui/waitingroom/makeroomcheckdialog/MakeRoomCheckFragmentDialog.kt
Labels: 🐷창환, fix, pull request

#443 #442 [대기방] 대기방 방 나가기 문구 변경
  app/src/main/res/layout/fragment_waiting_room.xml
  app/src/main/res/values/strings.xml
Labels: 🐷창환, fix, pull request

#444 #401 [대표사진 선택창] 첫 진입시 현재 썸네일에 테두리 및 대표 태그 보이게 설정
  .gitignore
  app/src/main/java/com/spark/android/ui/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/spark/android/ui/storage/adapter/CompleteVpAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/adapter/IncompleteVpAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/adapter/PhotoMainPickRvAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/adapter/ProgressingVpAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/photo/StoragePhotoCollectionActivity.kt
  app/src/main/java/com/spark/android/ui/storage/photo/StoragePhotoMainPickActivity.kt
  app/src/main/java/com/spark/android/ui/storage/viewmodel/PhotoViewModel.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/item_photo_main_pick_list.xml
  app/src/main/res/layout/item_storage_complete_list.xml
  app/src/main/res/layout/item_storage_incomplete_list.xml
Labels: 🐬호재, pull request

#447 #445,446 [방생성] 대기방 생성_인증방식 폰트 사이즈 수정+ 버튼 문구수정, 습관방생성_방이름 설정뷰 버튼 활성화 관계
  app/src/main/res/layout/fragment_name_setting.xml
  app/src/main/res/layout/fragment_select_confirm_method.xml
  app/src/main/res/values/strings.xml
Labels: 🐷창환, fix, pull request

#451 #450 [알림 센터] 레이아웃 및 스와이프 재설정
  app/src/main/java/com/spark/android/ui/alarmcenter/AlarmCenterActivity.kt
  app/src/main/res/layout/item_alarm_list.xml
Labels: 🦁연주, pull request

#453 #452 [회원가입 및 프로필 입력] 기본 이미지 설정 및 닉네임 입력 안됐을 시 버튼 비활성화
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileFragment.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/drawable-hdpi/ic_profile_photo.png
  app/src/main/res/drawable-mdpi/ic_profile_photo.png
  app/src/main/res/drawable-xhdpi/ic_profile_photo.png
  app/src/main/res/drawable-xxhdpi/ic_profile_photo.png
  app/src/main/res/drawable-xxxhdpi/ic_profile_photo.png
  app/src/main/res/drawable/ic_profile_empty.xml
  app/src/main/res/layout/fragment_profile.xml
Labels: 🦁연주, pull request

#455 #454 [신고하기] 뒤로가기 활성화 및 텍스트 필드 관련 기능 추가
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileFragment.kt
  app/src/main/java/com/spark/android/ui/feedreport/FeedReportActivity.kt
Labels: 🦁연주, pull request

#457 #456 [feat] 신고하기 버튼 클릭 후 & 신고하기 중 뒤로가기 클릭 후 피드 뷰로 돌아오도록 개선
  app/src/main/java/com/spark/android/ui/feedreport/FeedReportActivity.kt
  app/src/main/java/com/spark/android/ui/main/MainActivity.kt
Labels: 🦁연주, pull request

#460 #459 [피드] 리프레시 적용
  app/build.gradle
  app/src/main/java/com/spark/android/data/remote/repository/FeedRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/FeedRepositoryImpl.kt
  app/src/main/java/com/spark/android/ui/feed/FeedFragment.kt
  app/src/main/java/com/spark/android/ui/feed/FeedViewModel.kt
  app/src/main/java/com/spark/android/ui/feed/adapter/FeedAdapter.kt
  app/src/main/res/layout/fragment_feed.xml
Labels: 🦁연주, pull request

#463 #461 [홈] 리프레시 적용
  app/src/main/java/com/spark/android/ui/feed/FeedFragment.kt
  app/src/main/java/com/spark/android/ui/feed/FeedViewModel.kt
  app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
  app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_home_main.xml
Labels: 🦁연주, pull request

#465 #458 [홈_메인] 빨콩스 완료스
  app/src/main/java/com/spark/android/data/remote/datasource/RemoteHomeDataSource.kt
  app/src/main/java/com/spark/android/data/remote/datasource/RemoteHomeDataSourceImpl.kt
  app/src/main/java/com/spark/android/data/remote/entity/response/HomeNoticeRedDotResponese.kt
  app/src/main/java/com/spark/android/data/remote/repository/HomeRepository.kt
  app/src/main/java/com/spark/android/data/remote/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/spark/android/data/remote/service/HomeNoticeRedDotService.kt
  app/src/main/java/com/spark/android/di/RemoteDataSourceModule.kt
  app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt
  app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt
  app/src/main/res/drawable/ic_home_notice_red_dot.xml
  app/src/main/res/layout/fragment_home_main.xml
Labels: 🐷창환, feat, pull request

#468 #467 [feat] GA 트래킹 심는 Util 함수 제작
  app/src/main/java/com/spark/android/util/FirebaseLogUtil.kt
Labels: 🦁연주, pull request

#470 #449, 466, 469 [습관방] QA수정
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
  app/src/main/res/layout/activity_habit_goal_manage.xml
  app/src/main/res/layout/activity_habit_send_spark.xml
Labels: pull request

#471 #367,437 [fix] EventWrapper로 대기방 생성 삭제. onSuccess에 finish 달기
  app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt
  app/src/main/java/com/spark/android/ui/joincode/viewmodel/JoinCodeViewModel.kt
  app/src/main/java/com/spark/android/ui/makeroom/selectconfirmmethod/SelectConfirmMethodFragment.kt
  app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt
  app/src/main/java/com/spark/android/ui/setpurpose/viewmodel/SetPurposeViewModel.kt
  app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
  app/src/main/java/com/spark/android/ui/waitingroom/bottomsheet/WaitingRoomFragmentBottomSheet.kt
  app/src/main/java/com/spark/android/ui/waitingroom/makeroomcheckdialog/MakeRoomCheckFragmentDialog.kt
  app/src/main/java/com/spark/android/ui/waitingroom/viewmodel/WaitingRoomViewModel.kt
Labels: 🐷창환, fix, pull request

#473 #472 [feat] GA 클릭 이벤트 측정 방법 수정
  app/src/main/java/com/spark/android/util/FirebaseLogUtil.kt
Labels: 🦁연주, pull request

#475 #474 [fix] 나의 목표 관리 비정상 종료 수정
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/java/com/spark/android/util/BindingAdapters.kt
Labels: 🐉재훈, pull request

#477 #476 [fix] 습관방 생명 감소 알림 수정
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
Labels: 🐉재훈, pull request

#478 #400 [보관함] 뒤로가기 로직 수정
  app/src/main/java/com/spark/android/ui/main/MainActivity.kt
  app/src/main/java/com/spark/android/ui/storage/StorageCompleteFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StorageFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StorageIncompleteFragment.kt
  app/src/main/java/com/spark/android/ui/storage/StorageProgressingFragment.kt
  app/src/main/java/com/spark/android/ui/storage/adapter/CompleteVpAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/adapter/IncompleteVpAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/adapter/ProgressingVpAdapter.kt
  app/src/main/java/com/spark/android/ui/storage/photo/StoragePhotoCollectionActivity.kt
  app/src/main/java/com/spark/android/ui/storage/photo/StoragePhotoMainPickActivity.kt
  app/src/main/java/com/spark/android/ui/storage/viewmodel/StorageViewModel.kt
  app/src/main/res/navigation/main_nav_graph.xml
Labels: 🐬호재, feat, layout, pull request

#481 #480 [트래킹] GA 트래킹 연주 부분~!
  app/src/main/java/com/spark/android/SparkMessagingService.kt
  app/src/main/java/com/spark/android/ui/auth/profile/ProfileFragment.kt
  app/src/main/java/com/spark/android/ui/auth/signin/SignInFragment.kt
  app/src/main/java/com/spark/android/ui/feed/FeedViewModel.kt
  app/src/main/java/com/spark/android/ui/intro/IntroActivity.kt
  app/src/main/java/com/spark/android/ui/share/InstaShareDialogFragment.kt
  app/src/main/java/com/spark/android/util/FirebaseLogUtil.kt
Labels: 🦁연주, feat

#483 #482 [fix] 습관방 생명 감소 알림 개수 오류 수정
  app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
  app/src/main/java/com/spark/android/ui/habit/HabitLifeLessDialogFragment.kt
  app/src/main/res/layout/dialog_habit_life_less.xml
Labels: 🐉재훈, pull request

#486 #485 [목표 설정] 애니메이션 속도변경
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/spark/android/util/AnimationUtil.kt
Labels: 🐷창환, fix, pull request
